// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Top Title' | 'Feature Title' | 'Feature Text' | 'Feature Icon' // Variant
 * backgroundColor?: string // Background Color
 * border?: undefined // Border
 * text?: string // Text
 * cornerRadius?: undefined // Corner Radius
 * iconVisible?: 'Check' | 'Cancel' // Icon Visible
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-APDXW7PB.js";
import { className, css, fonts } from "../chunks/chunk-XVXSSQMC.js";
import { routes } from "../chunks/chunk-D65PBWLB.js";

// virtual:pricing/comparison-item
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/347T67SFzBTyQyi8hlfy/xJiPFq3OPvjGyJzEBXSw/L6rcvHFL4.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	RichText,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/fv3LkZ5C13QYLxqjxZg5/QP30mJzK4AZIiznwZILP/rs8unLVHV.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["lOu6N9Nrp", "RfnI9cOwl"];
var serializationHash = "framer-aTmBn";
var variantClassNames = {
	lOu6N9Nrp: "framer-v-1wi8a8b",
	RfnI9cOwl: "framer-v-1b3cpgd",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Cancel: "RfnI9cOwl",
	Check: "lOu6N9Nrp",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "lOu6N9Nrp",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "lOu6N9Nrp",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "RfnI9cOwl") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "RfnI9cOwl") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1wi8a8b",
							className3,
							classNames,
						)}
						data-framer-name={"Check"}
						layoutDependency={layoutDependency}
						layoutId={"lOu6N9Nrp"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								RfnI9cOwl: {
									"data-framer-name": "Cancel",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<SVG
								className={"framer-elqfv7"}
								data-framer-name={"Check"}
								fill={"rgba(0,0,0,1)"}
								intrinsicHeight={24}
								intrinsicWidth={24}
								layoutDependency={layoutDependency}
								layoutId={"SnZjQbMYl"}
								svg={
									'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12Z" stroke="#077331" stroke-width="1.5"/>\n<path d="M8 12.75C8 12.75 9.6 13.6625 10.4 15C10.4 15 12.8 9.75 16 8" stroke="#077331" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n</svg>\n'
								}
								withExternalLayout={true}
							/>
						)}
						{isDisplayed1() && (
							<SVG
								className={"framer-6aa57j"}
								data-framer-name={"Cancel"}
								fill={"rgba(0,0,0,1)"}
								intrinsicHeight={24}
								intrinsicWidth={24}
								layoutDependency={layoutDependency}
								layoutId={"TnA_7yXYz"}
								svg={
									'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M14.9994 15L9 9M9.00064 15L15 9" stroke="#FF1313" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>\n<path d="M22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12Z" stroke="#FF1313" stroke-width="1.5"/>\n</svg>\n'
								}
								withExternalLayout={true}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-aTmBn.framer-1svr6fw, .framer-aTmBn .framer-1svr6fw { display: block; }",
	".framer-aTmBn.framer-1wi8a8b { height: 24px; overflow: visible; position: relative; width: 24px; }",
	".framer-aTmBn .framer-elqfv7 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-aTmBn .framer-6aa57j { flex: none; height: 24px; left: 0px; position: absolute; top: 0px; width: 24px; }",
];
var Framerrs8unLVHV = withCSS(Component, css3, "framer-aTmBn");
var stdin_default = Framerrs8unLVHV;
Framerrs8unLVHV.displayName = "Pricing/Icon";
Framerrs8unLVHV.defaultProps = {
	height: 24,
	width: 24,
};
addPropertyControls(Framerrs8unLVHV, {
	variant: {
		options: ["lOu6N9Nrp", "RfnI9cOwl"],
		optionTitles: ["Check", "Cancel"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerrs8unLVHV,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/347T67SFzBTyQyi8hlfy/xJiPFq3OPvjGyJzEBXSw/L6rcvHFL4.js
var PricingIconFonts = getFonts(stdin_default);
var PricingIconControls = getPropertyControls(stdin_default);
var cycleOrder2 = ["e2wS_s3BU", "zRRuaKS1d", "IBa6A6DBC", "ULLGddExH"];
var serializationHash2 = "framer-v0c9y";
var variantClassNames2 = {
	e2wS_s3BU: "framer-v-mbepp9",
	IBa6A6DBC: "framer-v-qjy60t",
	ULLGddExH: "framer-v-1m18p8q",
	zRRuaKS1d: "framer-v-109v2ou",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var radiusForCorner = (value, cornerIndex) => {
	if (typeof value === "number" && Number.isFinite(value))
		return Math.max(0, value) + "px";
	if (typeof value !== "string" || typeof cornerIndex !== "number")
		return void 0;
	const segments = value.split(" ");
	return segments[cornerIndex] || segments[cornerIndex - 2] || segments[0];
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableEnumMap = {
	Cancel: "RfnI9cOwl",
	Check: "lOu6N9Nrp",
};
var humanReadableVariantMap2 = {
	"Feature Icon": "ULLGddExH",
	"Feature Text": "IBa6A6DBC",
	"Feature Title": "zRRuaKS1d",
	"Top Title": "e2wS_s3BU",
};
var getProps2 = ({
	backgroundColor,
	border,
	cornerRadius,
	height,
	iconVisible,
	id,
	text,
	width,
	...props
}) => {
	var _ref,
		_humanReadableEnumMap_iconVisible,
		_ref1,
		_ref2,
		_ref3,
		_ref4,
		_humanReadableVariantMap_props_variant,
		_ref5,
		_ref6;
	return {
		...props,
		IiBZpnSOA:
			(_ref =
				cornerRadius !== null && cornerRadius !== void 0
					? cornerRadius
					: props.IiBZpnSOA) !== null && _ref !== void 0
				? _ref
				: "0px",
		sgPKJemxL:
			(_ref2 =
				(_ref1 =
					(_humanReadableEnumMap_iconVisible =
						humanReadableEnumMap[iconVisible]) !== null &&
					_humanReadableEnumMap_iconVisible !== void 0
						? _humanReadableEnumMap_iconVisible
						: iconVisible) !== null && _ref1 !== void 0
					? _ref1
					: props.sgPKJemxL) !== null && _ref2 !== void 0
				? _ref2
				: "lOu6N9Nrp",
		tlS4qZX_b:
			(_ref3 = text !== null && text !== void 0 ? text : props.tlS4qZX_b) !==
				null && _ref3 !== void 0
				? _ref3
				: "Basic Plan",
		uYDTnqIfm:
			(_ref4 =
				backgroundColor !== null && backgroundColor !== void 0
					? backgroundColor
					: props.uYDTnqIfm) !== null && _ref4 !== void 0
				? _ref4
				: "var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
		variant:
			(_ref5 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap2[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref5 !== void 0
				? _ref5
				: "e2wS_s3BU",
		yvQ1xSprb:
			(_ref6 =
				border !== null && border !== void 0 ? border : props.yvQ1xSprb) !==
				null && _ref6 !== void 0
				? _ref6
				: {
						borderColor:
							'var(--token-de8a06a8-03a7-4559-b5c6-f6a9df9c6d66, rgb(236, 236, 236)) /* {"name":"Gray Stroke"} */',
						borderStyle: "solid",
						borderWidth: 1,
					},
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		uYDTnqIfm,
		yvQ1xSprb,
		tlS4qZX_b,
		IiBZpnSOA,
		sgPKJemxL,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "e2wS_s3BU",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "ULLGddExH") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "ULLGddExH") return true;
		return false;
	};
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [className, className2];
	const componentViewport = useComponentViewport2();
	var _yvQ1xSprb_borderBottomWidth,
		_yvQ1xSprb_borderLeftWidth,
		_yvQ1xSprb_borderRightWidth,
		_yvQ1xSprb_borderTopWidth;
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-mbepp9",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Top Title"}
						layoutDependency={layoutDependency}
						layoutId={"e2wS_s3BU"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width":
								((_yvQ1xSprb_borderBottomWidth =
									yvQ1xSprb.borderBottomWidth) !== null &&
								_yvQ1xSprb_borderBottomWidth !== void 0
									? _yvQ1xSprb_borderBottomWidth
									: yvQ1xSprb.borderWidth) + "px",
							"--border-color": yvQ1xSprb.borderColor,
							"--border-left-width":
								((_yvQ1xSprb_borderLeftWidth = yvQ1xSprb.borderLeftWidth) !==
									null && _yvQ1xSprb_borderLeftWidth !== void 0
									? _yvQ1xSprb_borderLeftWidth
									: yvQ1xSprb.borderWidth) + "px",
							"--border-right-width":
								((_yvQ1xSprb_borderRightWidth = yvQ1xSprb.borderRightWidth) !==
									null && _yvQ1xSprb_borderRightWidth !== void 0
									? _yvQ1xSprb_borderRightWidth
									: yvQ1xSprb.borderWidth) + "px",
							"--border-style": yvQ1xSprb.borderStyle,
							"--border-top-width":
								((_yvQ1xSprb_borderTopWidth = yvQ1xSprb.borderTopWidth) !==
									null && _yvQ1xSprb_borderTopWidth !== void 0
									? _yvQ1xSprb_borderTopWidth
									: yvQ1xSprb.borderWidth) + "px",
							backgroundColor: uYDTnqIfm,
							borderBottomLeftRadius: radiusForCorner(IiBZpnSOA, 3),
							borderBottomRightRadius: radiusForCorner(IiBZpnSOA, 2),
							borderTopLeftRadius: radiusForCorner(IiBZpnSOA, 0),
							borderTopRightRadius: radiusForCorner(IiBZpnSOA, 1),
							...style,
						}}
						{...addPropertyOverrides2(
							{
								IBa6A6DBC: {
									"data-framer-name": "Feature Text",
								},
								ULLGddExH: {
									"data-framer-name": "Feature Icon",
								},
								zRRuaKS1d: {
									"data-framer-name": "Feature Title",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1o2h249"}
								data-framer-name={"5 bills/month"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ewO_I0TeS"}
								style={{
									"--extracted-1w1cjl5":
										"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={tlS4qZX_b}
								variants={{
									IBa6A6DBC: {
										"--extracted-r6o4lv":
											"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
									},
									zRRuaKS1d: {
										"--extracted-r6o4lv":
											"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										IBa6A6DBC: {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-1hqv6yj"}
														data-styles-preset={"z7TVLwHMJ"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
														}}
													>
														{"Basic Plan"}
													</motion2.p>
												</React2.Fragment>
											),
										},
										zRRuaKS1d: {
											children: (
												<React2.Fragment>
													<motion2.p
														className={"framer-styles-preset-1hqv6yj"}
														data-styles-preset={"z7TVLwHMJ"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
														}}
													>
														<motion2.strong>{"Basic Plan"}</motion2.strong>
													</motion2.p>
												</React2.Fragment>
											),
											fonts: ["Inter", "Inter-Bold"],
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React2.Fragment>
									<motion2.h6
										className={"framer-styles-preset-1gntewp"}
										data-styles-preset={"K0scFfTq_"}
										style={{
											"--framer-text-color":
												"var(--extracted-1w1cjl5, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
										}}
									>
										{"Basic Plan"}
									</motion2.h6>
								</React2.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<ComponentViewportProvider
								{...addPropertyOverrides2(
									{
										ULLGddExH: {
											height: 24,
											width: "24px",
											y:
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) +
												(16 +
													(((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 56) -
														32 -
														24) /
														2),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion2.div
									className={"framer-13zqyrw-container"}
									layoutDependency={layoutDependency}
									layoutId={"P7pxUGVxY-container"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "P7pxUGVxY",
										layoutId: "P7pxUGVxY",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: sgPKJemxL,
										width: "100%",
									})}
								</motion2.div>
							</ComponentViewportProvider>
						)}
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-v0c9y.framer-1eardji, .framer-v0c9y .framer-1eardji { display: block; }",
	".framer-v0c9y.framer-mbepp9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px; position: relative; width: min-content; }",
	".framer-v0c9y .framer-1o2h249 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-v0c9y .framer-13zqyrw-container { flex: none; height: 24px; position: relative; width: 24px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-v0c9y.framer-mbepp9 { gap: 0px; } .framer-v0c9y.framer-mbepp9 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-v0c9y.framer-mbepp9 > :first-child { margin-left: 0px; } .framer-v0c9y.framer-mbepp9 > :last-child { margin-right: 0px; } }",
	...css,
	...css2,
	'.framer-v0c9y[data-border="true"]::after, .framer-v0c9y [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerL6rcvHFL4 = withCSS2(Component2, css4, "framer-v0c9y");
var stdin_default2 = FramerL6rcvHFL4;
FramerL6rcvHFL4.displayName = "Pricing/Comparison Item";
FramerL6rcvHFL4.defaultProps = {
	height: 64,
	width: 133.5,
};
addPropertyControls2(FramerL6rcvHFL4, {
	variant: {
		options: ["e2wS_s3BU", "zRRuaKS1d", "IBa6A6DBC", "ULLGddExH"],
		optionTitles: [
			"Top Title",
			"Feature Title",
			"Feature Text",
			"Feature Icon",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	uYDTnqIfm: {
		defaultValue:
			'var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)) /* {"name":"White"} */',
		title: "Background Color",
		type: ControlType2.Color,
	},
	yvQ1xSprb: {
		defaultValue: {
			borderColor:
				'var(--token-de8a06a8-03a7-4559-b5c6-f6a9df9c6d66, rgb(236, 236, 236)) /* {"name":"Gray Stroke"} */',
			borderStyle: "solid",
			borderWidth: 1,
		},
		title: "Border",
		type: ControlType2.Border,
	},
	tlS4qZX_b: {
		defaultValue: "Basic Plan",
		displayTextArea: false,
		title: "Text",
		type: ControlType2.String,
	},
	IiBZpnSOA: {
		defaultValue: "0px",
		title: "Corner Radius",
		type: ControlType2.BorderRadius,
	},
	sgPKJemxL: (PricingIconControls === null || PricingIconControls === void 0
		? void 0
		: PricingIconControls["variant"]) && {
		...PricingIconControls["variant"],
		defaultValue: "lOu6N9Nrp",
		description: void 0,
		hidden: void 0,
		title: "Icon Visible",
	},
});
addFonts2(
	FramerL6rcvHFL4,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...PricingIconFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:pricing/comparison-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {
	base: "IBa6A6DBC",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ComparisonItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var comparison_item_default = ComponentWithRoot;
export { comparison_item_default as default };
