// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Monthly - Desktop' | 'Yearly - Desktop' | 'Monthly - Small' | 'Yearly - Small' // Variant
 * cardDirection?: 'Horizontal' | 'Vertical' // Card Direction
}} Props

 */
import { stdin_default } from "../chunks/chunk-DXOQQ7B4.js";
import "../chunks/chunk-NYXTUNPH.js";
import "../chunks/chunk-HR56UER2.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-APDXW7PB.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "../chunks/chunk-6X7ZQ6K6.js";
import { className, css, fonts } from "../chunks/chunk-5ETCZXGB.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-XVXSSQMC.js";
import { routes } from "../chunks/chunk-D65PBWLB.js";

// virtual:pricing/deck
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/A6H7vRQv7BTLz9s0stRC/j5s42xeHNlfhDoBlFwnu/SAc3djdp_.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	RichText as RichText2,
	useActiveVariantCallback,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/v4RcZz5v1ifxsZFf35W8/UVP6I1m7ogGkn0BDxfAD/rmlwIKDLa.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	ResolveLinks,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ButtonMainFonts = getFonts(stdin_default);
var ButtonMainControls = getPropertyControls(stdin_default);
var serializationHash = "framer-BE28R";
var variantClassNames = {
	k8WuEHtU1: "framer-v-1egl09l",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableEnumMap = {
	"Primary (Green) S": "hmIfpyYO2",
	"Primary (Green)": "im5jNJ3bR",
	"Secondary (Dark)": "Q4k0YE_5y",
	"Secondary S (Dark)": "ieHFVBzki",
	"Tertiary (White) S": "MhqxzY_NJ",
	"Tertiary (White)": "uTxoYe99S",
};
var getProps = ({
	buttonVariant,
	height,
	id,
	list1,
	list2,
	list3,
	list4,
	planName,
	pricing,
	subtitle,
	width,
	...props
}) => {
	return {
		...props,
		A5aOoa8RT: subtitle ?? props.A5aOoa8RT ?? "Free for personal use",
		IPLfOmgdz: list3 ?? props.IPLfOmgdz ?? "Basic Financial Reports",
		k41PurcFD: list1 ?? props.k41PurcFD ?? "Income & Expense Tracking",
		M8z8Du4fv: list2 ?? props.M8z8Du4fv ?? "Bill Pay & Reminders",
		OCygUiG1i: pricing ?? props.OCygUiG1i ?? "$0",
		U5EzjX5r5:
			humanReadableEnumMap[buttonVariant] ??
			buttonVariant ??
			props.U5EzjX5r5 ??
			"uTxoYe99S",
		VViy8500X: planName ?? props.VViy8500X ?? "Basic Plan",
		yOcTeBVUN: list4 ?? props.yOcTeBVUN ?? "Budget Planning & Community",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants = motion.create(React.Fragment);
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		VViy8500X,
		OCygUiG1i,
		A5aOoa8RT,
		k41PurcFD,
		M8z8Du4fv,
		IPLfOmgdz,
		yOcTeBVUN,
		U5EzjX5r5,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "k8WuEHtU1",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className4, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const router = useRouter();
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1egl09l",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"k8WuEHtU1"}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-de8a06a8-03a7-4559-b5c6-f6a9df9c6d66, rgb(236, 236, 236))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
					>
						<motion.div
							className={"framer-1ds3hbd"}
							data-framer-name={"Title Text"}
							layoutDependency={layoutDependency}
							layoutId={"gGS_HN6jG"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-qrfa16"}
								data-framer-name={"Basic Plan"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ubDJWJNqx"}
								style={{
									"--extracted-1w1cjl5":
										"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={VViy8500X}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-1gntewp"}
										data-styles-preset={"K0scFfTq_"}
										style={{
											"--framer-text-color":
												"var(--extracted-1w1cjl5, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
										}}
									>
										{"Basic Plan"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-1kelckq"}
								data-framer-name={"Price"}
								layoutDependency={layoutDependency}
								layoutId={"J5eNqX6h7"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1gqdlbi"}
									data-framer-name={"$0"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"G3Ah5KGet"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={OCygUiG1i}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h2
											className={"framer-styles-preset-1tp96gq"}
											data-styles-preset={"UrM4nywSg"}
										>
											{"$0"}
										</motion.h2>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1wp1chm"}
									data-framer-name={"Free for personal use"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"hwWbDL218"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(77, 79, 78))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={A5aOoa8RT}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(77, 79, 78)))",
											}}
										>
											{"Free for personal use"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<SVG
							className={"framer-1s0u4ch"}
							data-framer-name={"Line"}
							fill={
								"var(--token-de8a06a8-03a7-4559-b5c6-f6a9df9c6d66, rgb(236, 236, 236))"
							}
							intrinsicHeight={3}
							intrinsicWidth={338}
							layoutDependency={layoutDependency}
							layoutId={"C9H5pj1FH"}
							svg={
								'<svg width="338" height="3" viewBox="-1 -1 338 3" fill="none" xmlns="http://www.w3.org/2000/svg">\n<line y1="0.5" x2="336" y2="0.5" stroke="#ECECEC"/>\n</svg>\n'
							}
							withExternalLayout={true}
						/>
						<motion.div
							className={"framer-3ipbrr"}
							data-framer-name={"Lists"}
							layoutDependency={layoutDependency}
							layoutId={"sWENVvtG9"}
						>
							<motion.div
								className={"framer-p1decu"}
								data-framer-name={"1"}
								layoutDependency={layoutDependency}
								layoutId={"NvL8eYQ3n"}
							>
								<SVG
									className={"framer-oicrsj"}
									data-framer-name={"Check Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"SrpvjRYPA"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 36"><path d="M 18.338 18 C 18.338 13.398 14.607 9.666 10.005 9.666 C 5.403 9.666 1.672 13.398 1.672 18 C 1.672 22.602 5.403 26.333 10.005 26.333 C 14.607 26.333 18.338 22.602 18.338 18 Z" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 6.672 18.625 C 6.672 18.625 8.005 19.385 8.672 20.5 C 8.672 20.5 10.672 16.125 13.338 14.666" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
									}
									svgContentId={8918592563}
									withExternalLayout={true}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-10w1rwm"}
									data-framer-name={"Income & Expense Tracking"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"TnhjPNqtX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={k41PurcFD}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
											}}
										>
											{"Income & Expense Tracking"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1qp4kd"}
								data-framer-name={"2"}
								layoutDependency={layoutDependency}
								layoutId={"GJSq9x8Uo"}
							>
								<SVG
									className={"framer-7hysvl"}
									data-framer-name={"Check Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"XJ9q0Ieya"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 36"><path d="M 18.338 18 C 18.338 13.398 14.607 9.666 10.005 9.666 C 5.403 9.666 1.672 13.398 1.672 18 C 1.672 22.602 5.403 26.333 10.005 26.333 C 14.607 26.333 18.338 22.602 18.338 18 Z" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 6.672 18.625 C 6.672 18.625 8.005 19.385 8.672 20.5 C 8.672 20.5 10.672 16.125 13.338 14.666" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
									}
									svgContentId={8918592563}
									withExternalLayout={true}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1hh42n1"}
									data-framer-name={"Bill Pay & Reminders"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"qhPj1G3N3"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={M8z8Du4fv}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
											}}
										>
											{"Bill Pay & Reminders"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1y45tim"}
								data-framer-name={"3"}
								layoutDependency={layoutDependency}
								layoutId={"vWEzvViPu"}
							>
								<SVG
									className={"framer-axzop2"}
									data-framer-name={"Check Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"FgVXu_ypw"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 36"><path d="M 18.338 18 C 18.338 13.398 14.607 9.666 10.005 9.666 C 5.403 9.666 1.672 13.398 1.672 18 C 1.672 22.602 5.403 26.333 10.005 26.333 C 14.607 26.333 18.338 22.602 18.338 18 Z" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 6.672 18.625 C 6.672 18.625 8.005 19.385 8.672 20.5 C 8.672 20.5 10.672 16.125 13.338 14.666" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
									}
									svgContentId={8918592563}
									withExternalLayout={true}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-t62a3e"}
									data-framer-name={"Basic Financial Reports"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"aLTxC2kfL"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={IPLfOmgdz}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
											}}
										>
											{"Basic Financial Reports"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-nlstpn"}
								data-framer-name={"4"}
								layoutDependency={layoutDependency}
								layoutId={"eCiBDm9FD"}
							>
								<SVG
									className={"framer-ooyz3c"}
									data-framer-name={"Check Icon"}
									layout={"position"}
									layoutDependency={layoutDependency}
									layoutId={"TN0sj_Pfa"}
									opacity={1}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 36"><path d="M 18.338 18 C 18.338 13.398 14.607 9.666 10.005 9.666 C 5.403 9.666 1.672 13.398 1.672 18 C 1.672 22.602 5.403 26.333 10.005 26.333 C 14.607 26.333 18.338 22.602 18.338 18 Z" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-miterlimit="10" stroke-dasharray=""></path><path d="M 6.672 18.625 C 6.672 18.625 8.005 19.385 8.672 20.5 C 8.672 20.5 10.672 16.125 13.338 14.666" fill="transparent" stroke-width="1.25" stroke="var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></svg>'
									}
									svgContentId={8918592563}
									withExternalLayout={true}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1tum9uz"}
									data-framer-name={"Budget Planning & Community"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"q_Ga85JrV"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={yOcTeBVUN}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
											}}
										>
											{"Budget Planning & Community"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "L3F_ZUarC",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks) => (
								<ComponentViewportProvider
									height={57}
									width={`calc(${componentViewport?.width || "100vw"} - 64px)`}
									y={(componentViewport?.y || 0) + 40 + 897.4}
								>
									<motion.div
										className={"framer-174io75-container"}
										layoutDependency={layoutDependency}
										layoutId={"FhmvEY2Yd-container"}
									>
										{_jsx(stdin_default, {
											dua84ABRH: "arrow-right",
											height: "100%",
											icFgcTrRS: resolvedLinks[0],
											id: "FhmvEY2Yd",
											layoutId: "FhmvEY2Yd",
											NEhkXVPkj: "Get Started Now",
											style: {
												width: "100%",
											},
											UnIhK_sDa: false,
											variant: U5EzjX5r5,
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
							)}
						</ResolveLinks>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-BE28R.framer-1u57k5, .framer-BE28R .framer-1u57k5 { display: block; }",
	".framer-BE28R.framer-1egl09l { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-start; overflow: visible; padding: 40px 32px 40px 32px; position: relative; width: 361px; }",
	".framer-BE28R .framer-1ds3hbd, .framer-BE28R .framer-3ipbrr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BE28R .framer-qrfa16, .framer-BE28R .framer-1gqdlbi, .framer-BE28R .framer-1wp1chm { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-BE28R .framer-1kelckq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BE28R .framer-1s0u4ch { flex: none; height: 3px; position: relative; width: 100%; }",
	".framer-BE28R .framer-p1decu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BE28R .framer-oicrsj, .framer-BE28R .framer-7hysvl, .framer-BE28R .framer-axzop2, .framer-BE28R .framer-ooyz3c { flex: none; height: 36px; position: relative; width: 20px; }",
	".framer-BE28R .framer-10w1rwm, .framer-BE28R .framer-1hh42n1, .framer-BE28R .framer-t62a3e, .framer-BE28R .framer-1tum9uz { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-BE28R .framer-1qp4kd, .framer-BE28R .framer-1y45tim, .framer-BE28R .framer-nlstpn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-BE28R .framer-174io75-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-BE28R.framer-1egl09l, .framer-BE28R .framer-1ds3hbd, .framer-BE28R .framer-1kelckq, .framer-BE28R .framer-3ipbrr, .framer-BE28R .framer-p1decu, .framer-BE28R .framer-1qp4kd, .framer-BE28R .framer-1y45tim, .framer-BE28R .framer-nlstpn { gap: 0px; } .framer-BE28R.framer-1egl09l > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-BE28R.framer-1egl09l > :first-child, .framer-BE28R .framer-1ds3hbd > :first-child, .framer-BE28R .framer-1kelckq > :first-child, .framer-BE28R .framer-3ipbrr > :first-child { margin-top: 0px; } .framer-BE28R.framer-1egl09l > :last-child, .framer-BE28R .framer-1ds3hbd > :last-child, .framer-BE28R .framer-1kelckq > :last-child, .framer-BE28R .framer-3ipbrr > :last-child { margin-bottom: 0px; } .framer-BE28R .framer-1ds3hbd > *, .framer-BE28R .framer-3ipbrr > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-BE28R .framer-1kelckq > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-BE28R .framer-p1decu > *, .framer-BE28R .framer-1qp4kd > *, .framer-BE28R .framer-1y45tim > *, .framer-BE28R .framer-nlstpn > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-BE28R .framer-p1decu > :first-child, .framer-BE28R .framer-1qp4kd > :first-child, .framer-BE28R .framer-1y45tim > :first-child, .framer-BE28R .framer-nlstpn > :first-child { margin-left: 0px; } .framer-BE28R .framer-p1decu > :last-child, .framer-BE28R .framer-1qp4kd > :last-child, .framer-BE28R .framer-1y45tim > :last-child, .framer-BE28R .framer-nlstpn > :last-child { margin-right: 0px; } }",
	...css2,
	...css4,
	...css,
	'.framer-BE28R[data-border="true"]::after, .framer-BE28R [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerrmlwIKDLa = withCSS(Component, css5, "framer-BE28R");
var stdin_default2 = FramerrmlwIKDLa;
FramerrmlwIKDLa.displayName = "Pricing/Single Card";
FramerrmlwIKDLa.defaultProps = {
	height: 564,
	width: 361,
};
addPropertyControls(FramerrmlwIKDLa, {
	VViy8500X: {
		defaultValue: "Basic Plan",
		displayTextArea: false,
		title: "Plan Name",
		type: ControlType.String,
	},
	OCygUiG1i: {
		defaultValue: "$0",
		displayTextArea: false,
		title: "Pricing",
		type: ControlType.String,
	},
	A5aOoa8RT: {
		defaultValue: "Free for personal use",
		displayTextArea: false,
		title: "Subtitle",
		type: ControlType.String,
	},
	k41PurcFD: {
		defaultValue: "Income & Expense Tracking",
		displayTextArea: false,
		title: "List 1",
		type: ControlType.String,
	},
	M8z8Du4fv: {
		defaultValue: "Bill Pay & Reminders",
		displayTextArea: false,
		title: "List 2",
		type: ControlType.String,
	},
	IPLfOmgdz: {
		defaultValue: "Basic Financial Reports",
		displayTextArea: false,
		title: "List 3",
		type: ControlType.String,
	},
	yOcTeBVUN: {
		defaultValue: "Budget Planning & Community",
		displayTextArea: false,
		title: "List 4",
		type: ControlType.String,
	},
	U5EzjX5r5: ButtonMainControls?.["variant"] && {
		...ButtonMainControls["variant"],
		defaultValue: "uTxoYe99S",
		description: void 0,
		hidden: void 0,
		title: "Button Variant",
	},
});
addFonts(
	FramerrmlwIKDLa,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonMainFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/A6H7vRQv7BTLz9s0stRC/j5s42xeHNlfhDoBlFwnu/SAc3djdp_.js
var PricingSingleCardFonts = getFonts2(stdin_default2);
var cycleOrder = ["HDhMix8q3", "VgmdicyHf", "or5YGbWPw", "XB4ut0veD"];
var serializationHash2 = "framer-vQDOo";
var variantClassNames2 = {
	HDhMix8q3: "framer-v-348knl",
	or5YGbWPw: "framer-v-pau4ak",
	VgmdicyHf: "framer-v-1s6vyvj",
	XB4ut0veD: "framer-v-14j79vg",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableEnumMap2 = {
	Horizontal: "row",
	Vertical: "column",
};
var humanReadableVariantMap = {
	"Monthly - Desktop": "HDhMix8q3",
	"Monthly - Small": "or5YGbWPw",
	"Yearly - Desktop": "VgmdicyHf",
	"Yearly - Small": "XB4ut0veD",
};
var getProps2 = ({ cardDirection, height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "HDhMix8q3",
		WFKdEZEQl:
			humanReadableEnumMap2[cardDirection] ??
			cardDirection ??
			props.WFKdEZEQl ??
			"row",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants2 = motion2.create(React2.Fragment);
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		WFKdEZEQl,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "HDhMix8q3",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1f5trdo = activeVariantCallback(async (...args) => {
		setVariant("HDhMix8q3");
	});
	const onTap1rnqcrs = activeVariantCallback(async (...args) => {
		setVariant("or5YGbWPw");
	});
	const onTaph17xpx = activeVariantCallback(async (...args) => {
		setVariant("VgmdicyHf");
	});
	const onTapcseqlm = activeVariantCallback(async (...args) => {
		setVariant("XB4ut0veD");
	});
	const sharedStyleClassNames = [className, className3];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-348knl",
							className5,
							classNames,
						)}
						data-framer-name={"Monthly - Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"HDhMix8q3"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								or5YGbWPw: {
									"data-framer-name": "Monthly - Small",
								},
								VgmdicyHf: {
									"data-framer-name": "Yearly - Desktop",
								},
								XB4ut0veD: {
									"data-framer-name": "Yearly - Small",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1shkqxj"}
							data-border={true}
							data-framer-name={"Month/Year Toggle"}
							layoutDependency={layoutDependency}
							layoutId={"sDin23THY"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-de8a06a8-03a7-4559-b5c6-f6a9df9c6d66, rgb(236, 236, 236))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
								borderBottomLeftRadius: 60,
								borderBottomRightRadius: 60,
								borderTopLeftRadius: 60,
								borderTopRightRadius: 60,
							}}
						>
							<motion2.div
								className={"framer-1be1k1q"}
								data-framer-name={"Button"}
								layoutDependency={layoutDependency}
								layoutId={"sBEL2mtnZ"}
								style={{
									backgroundColor:
										"var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))",
									borderBottomLeftRadius: 40,
									borderBottomRightRadius: 40,
									borderTopLeftRadius: 40,
									borderTopRightRadius: 40,
								}}
								variants={{
									VgmdicyHf: {
										backgroundColor: "rgba(7, 115, 49, 0)",
									},
									XB4ut0veD: {
										backgroundColor:
											"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
									},
								}}
								{...addPropertyOverrides(
									{
										VgmdicyHf: {
											"data-highlight": true,
											onTap: onTap1f5trdo,
										},
										XB4ut0veD: {
											"data-highlight": true,
											onTap: onTap1rnqcrs,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-jdmgy6"}
									data-framer-name={"Monthly"}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"PGyktQ0oe"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										VgmdicyHf: {
											"--extracted-r6o4lv":
												"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
										},
										XB4ut0veD: {
											"--extracted-r6o4lv":
												"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											VgmdicyHf: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-1dij33p"}
															data-styles-preset={"O45eiJOu6"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
															}}
														>
															<motion2.strong>{"Monthly"}</motion2.strong>
														</motion2.p>
													</React2.Fragment>
												),
											},
											XB4ut0veD: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-1dij33p"}
															data-styles-preset={"O45eiJOu6"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
															}}
														>
															<motion2.strong>{"Monthly"}</motion2.strong>
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)))",
											}}
										>
											<motion2.strong>{"Monthly"}</motion2.strong>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
							<motion2.div
								className={"framer-l61a6l"}
								data-framer-name={"Button"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"uXVQ2VuId"}
								onTap={onTaph17xpx}
								style={{
									backgroundColor: "rgba(7, 115, 49, 0)",
									borderBottomLeftRadius: 40,
									borderBottomRightRadius: 40,
									borderTopLeftRadius: 40,
									borderTopRightRadius: 40,
								}}
								variants={{
									VgmdicyHf: {
										backgroundColor: "rgb(7, 115, 49)",
									},
									XB4ut0veD: {
										backgroundColor:
											"var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))",
									},
								}}
								{...addPropertyOverrides(
									{
										or5YGbWPw: {
											onTap: onTapcseqlm,
										},
										XB4ut0veD: {
											"data-highlight": void 0,
											onTap: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-mk3f07"}
									data-framer-name={"Yearly"}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"LbiK2O2v6"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
										"--framer-paragraph-spacing": "0px",
									}}
									variants={{
										VgmdicyHf: {
											"--extracted-r6o4lv":
												"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
										},
										XB4ut0veD: {
											"--extracted-r6o4lv":
												"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											VgmdicyHf: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-1dij33p"}
															data-styles-preset={"O45eiJOu6"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)))",
															}}
														>
															<motion2.strong>{"Yearly"}</motion2.strong>
														</motion2.p>
													</React2.Fragment>
												),
											},
											XB4ut0veD: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-1dij33p"}
															data-styles-preset={"O45eiJOu6"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)))",
															}}
														>
															<motion2.strong>{"Yearly"}</motion2.strong>
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
											}}
										>
											<motion2.strong>{"Yearly"}</motion2.strong>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-1gykt6g"}
							data-framer-name={"Price card"}
							layoutDependency={layoutDependency}
							layoutId={"A_yg21XxS"}
							style={{
								"--19ou8c6": WFKdEZEQl === "column" ? "100%" : "1px",
								"--1d4dtka": WFKdEZEQl === "column" ? 0 : "calc(24px / 2)",
								"--1dtsauh": WFKdEZEQl,
								"--ej04vh": WFKdEZEQl === "row" ? 0 : "calc(24px / 2)",
								"--kp0edv": WFKdEZEQl === "column" ? void 0 : "1 0 0px",
							}}
						>
							<ComponentViewportProvider2
								height={564}
								width={
									WFKdEZEQl === "row"
										? `max((${componentViewport?.width || "100vw"} - 430px) / 2, 1px)`
										: componentViewport?.width || "100vw"
								}
								{...addPropertyOverrides(
									{
										or5YGbWPw: {
											width: "360px",
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 1892) - 0 - 2007.6) /
													2 +
													57.6 +
													24) +
												0 +
												0,
										},
										XB4ut0veD: {
											width: "360px",
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 1892) - 0 - 2007.6) /
													2 +
													57.6 +
													24) +
												0 +
												0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion2.div
									className={"framer-1nauqcc-container"}
									layoutDependency={layoutDependency}
									layoutId={"G2HO0vTVk-container"}
								>
									{_jsx2(stdin_default2, {
										A5aOoa8RT: "Free for personal use",
										height: "100%",
										id: "G2HO0vTVk",
										IPLfOmgdz: "Basic Financial Reports",
										k41PurcFD: "Income & Expense Tracking",
										layoutId: "G2HO0vTVk",
										M8z8Du4fv: "Bill Pay & Reminders",
										OCygUiG1i: "$0",
										style: {
											width: "100%",
										},
										U5EzjX5r5: "uTxoYe99S",
										VViy8500X: "Basic Plan",
										width: "100%",
										yOcTeBVUN: "Budget Planning & Community",
									})}
								</motion2.div>
							</ComponentViewportProvider2>
							<motion2.div
								className={"framer-1g8ylf5"}
								data-framer-name={"Pro"}
								layoutDependency={layoutDependency}
								layoutId={"THsgSJnuo"}
								style={{
									backgroundColor:
										"var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
								}}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-ur52h0"}
									data-framer-name={"Most Popular"}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"q7qC4ATUt"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1hqv6yj"}
											data-styles-preset={"z7TVLwHMJ"}
											style={{
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)))",
											}}
										>
											<motion2.strong>{"Most Popular"}</motion2.strong>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<ComponentViewportProvider2
									height={564}
									width={"350px"}
									{...addPropertyOverrides(
										{
											or5YGbWPw: {
												width: "328px",
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 1892) - 0 - 2007.6) /
														2 +
														57.6 +
														24) +
													0 +
													588 +
													16 +
													154,
											},
											XB4ut0veD: {
												width: "328px",
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 1892) - 0 - 2007.6) /
														2 +
														57.6 +
														24) +
													0 +
													588 +
													16 +
													154,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<motion2.div
										className={"framer-vmoqjl-container"}
										layoutDependency={layoutDependency}
										layoutId={"o9jJWp15t-container"}
									>
										{_jsx2(stdin_default2, {
											A5aOoa8RT: "For startups, billed monthly",
											height: "100%",
											id: "o9jJWp15t",
											IPLfOmgdz: "Advanced Financial Reports",
											k41PurcFD: "Everything in the Basic Plan",
											layoutId: "o9jJWp15t",
											M8z8Du4fv: "Unlimited Bill Pay & Reminders",
											OCygUiG1i: "$99",
											style: {
												width: "100%",
											},
											U5EzjX5r5: "im5jNJ3bR",
											VViy8500X: "Pro Plan",
											width: "100%",
											yOcTeBVUN: "Dedicated Customer Support",
											...addPropertyOverrides(
												{
													VgmdicyHf: {
														OCygUiG1i: "$79",
													},
													XB4ut0veD: {
														OCygUiG1i: "$79",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</motion2.div>
								</ComponentViewportProvider2>
							</motion2.div>
							<ComponentViewportProvider2
								height={564}
								width={
									WFKdEZEQl === "row"
										? `max((${componentViewport?.width || "100vw"} - 430px) / 2, 1px)`
										: componentViewport?.width || "100vw"
								}
								{...addPropertyOverrides(
									{
										or5YGbWPw: {
											width: "360px",
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 1892) - 0 - 2007.6) /
													2 +
													57.6 +
													24) +
												0 +
												1362,
										},
										XB4ut0veD: {
											width: "360px",
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 1892) - 0 - 2007.6) /
													2 +
													57.6 +
													24) +
												0 +
												1362,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<motion2.div
									className={"framer-1k31bkw-container"}
									layoutDependency={layoutDependency}
									layoutId={"jTkvdoVW6-container"}
								>
									{_jsx2(stdin_default2, {
										A5aOoa8RT: "For scaling, billed monthly",
										height: "100%",
										id: "jTkvdoVW6",
										IPLfOmgdz: "Financial Reports & KPIs",
										k41PurcFD: "All features from Pro Plan",
										layoutId: "jTkvdoVW6",
										M8z8Du4fv: "Team Collaboration Tools",
										OCygUiG1i: "$275",
										style: {
											width: "100%",
										},
										U5EzjX5r5: "uTxoYe99S",
										VViy8500X: "Enterprise Plan",
										width: "100%",
										yOcTeBVUN: "Dedicated Customer Support",
										...addPropertyOverrides(
											{
												VgmdicyHf: {
													OCygUiG1i: "$160",
												},
												XB4ut0veD: {
													OCygUiG1i: "$160",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</ComponentViewportProvider2>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vQDOo.framer-1e48x6o, .framer-vQDOo .framer-1e48x6o { display: block; }",
	".framer-vQDOo.framer-348knl { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1152px; overflow: hidden; padding: 0px; position: relative; width: 1152px; }",
	".framer-vQDOo .framer-1shkqxj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-vQDOo .framer-1be1k1q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 8px 24px 8px 24px; position: relative; width: min-content; }",
	".framer-vQDOo .framer-jdmgy6, .framer-vQDOo .framer-mk3f07 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-vQDOo .framer-l61a6l { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 8px 24px 8px 24px; position: relative; width: min-content; }",
	".framer-vQDOo .framer-1gykt6g { align-content: center; align-items: center; display: flex; flex: none; flex-direction: var(--1dtsauh); flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-vQDOo .framer-1nauqcc-container, .framer-vQDOo .framer-1k31bkw-container { flex: var(--kp0edv); height: auto; position: relative; width: var(--19ou8c6); }",
	".framer-vQDOo .framer-1g8ylf5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 16px; position: relative; width: 382px; }",
	".framer-vQDOo .framer-ur52h0 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-vQDOo .framer-vmoqjl-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vQDOo.framer-348knl, .framer-vQDOo .framer-1shkqxj, .framer-vQDOo .framer-1be1k1q, .framer-vQDOo .framer-l61a6l, .framer-vQDOo .framer-1gykt6g, .framer-vQDOo .framer-1g8ylf5 { gap: 0px; } .framer-vQDOo.framer-348knl > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-vQDOo.framer-348knl > :first-child, .framer-vQDOo .framer-1g8ylf5 > :first-child { margin-top: 0px; } .framer-vQDOo.framer-348knl > :last-child, .framer-vQDOo .framer-1g8ylf5 > :last-child { margin-bottom: 0px; } .framer-vQDOo .framer-1shkqxj > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-vQDOo .framer-1shkqxj > :first-child, .framer-vQDOo .framer-1be1k1q > :first-child, .framer-vQDOo .framer-l61a6l > :first-child { margin-left: 0px; } .framer-vQDOo .framer-1shkqxj > :last-child, .framer-vQDOo .framer-1be1k1q > :last-child, .framer-vQDOo .framer-l61a6l > :last-child { margin-right: 0px; } .framer-vQDOo .framer-1be1k1q > *, .framer-vQDOo .framer-l61a6l > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-vQDOo .framer-1gykt6g > * { margin-bottom: var(--ej04vh); margin-left: var(--1d4dtka); margin-right: var(--1d4dtka); margin-top: var(--ej04vh); } .framer-vQDOo .framer-1gykt6g > :first-child { margin-left: 0px; margin-top: 0px; } .framer-vQDOo .framer-1gykt6g > :last-child { margin-bottom: 0px; margin-right: 0px; } .framer-vQDOo .framer-1g8ylf5 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	".framer-vQDOo.framer-v-1s6vyvj .framer-1be1k1q, .framer-vQDOo.framer-v-14j79vg .framer-1be1k1q { cursor: pointer; }",
	".framer-vQDOo.framer-v-pau4ak.framer-348knl, .framer-vQDOo.framer-v-14j79vg.framer-348knl { width: 390px; }",
	".framer-vQDOo.framer-v-pau4ak .framer-1gykt6g, .framer-vQDOo.framer-v-14j79vg .framer-1gykt6g { flex-direction: column; width: 360px; }",
	".framer-vQDOo.framer-v-pau4ak .framer-1nauqcc-container, .framer-vQDOo.framer-v-pau4ak .framer-1k31bkw-container, .framer-vQDOo.framer-v-14j79vg .framer-1nauqcc-container, .framer-vQDOo.framer-v-14j79vg .framer-1k31bkw-container { flex: none; width: 100%; }",
	".framer-vQDOo.framer-v-pau4ak .framer-1g8ylf5, .framer-vQDOo.framer-v-14j79vg .framer-1g8ylf5 { width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vQDOo.framer-v-pau4ak .framer-1gykt6g { gap: 0px; } .framer-vQDOo.framer-v-pau4ak .framer-1gykt6g > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-vQDOo.framer-v-pau4ak .framer-1gykt6g > :first-child { margin-top: 0px; } .framer-vQDOo.framer-v-pau4ak .framer-1gykt6g > :last-child { margin-bottom: 0px; } }",
	".framer-vQDOo.framer-v-14j79vg .framer-l61a6l { cursor: unset; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vQDOo.framer-v-14j79vg .framer-1gykt6g { gap: 0px; } .framer-vQDOo.framer-v-14j79vg .framer-1gykt6g > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-vQDOo.framer-v-14j79vg .framer-1gykt6g > :first-child { margin-top: 0px; } .framer-vQDOo.framer-v-14j79vg .framer-1gykt6g > :last-child { margin-bottom: 0px; } }",
	...css,
	...css3,
	'.framer-vQDOo[data-border="true"]::after, .framer-vQDOo [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerSAc3djdp_ = withCSS2(Component2, css6, "framer-vQDOo");
var stdin_default3 = FramerSAc3djdp_;
FramerSAc3djdp_.displayName = "Pricing/Deck";
FramerSAc3djdp_.defaultProps = {
	height: 716,
	width: 1152,
};
addPropertyControls2(FramerSAc3djdp_, {
	variant: {
		options: ["HDhMix8q3", "VgmdicyHf", "or5YGbWPw", "XB4ut0veD"],
		optionTitles: [
			"Monthly - Desktop",
			"Yearly - Desktop",
			"Monthly - Small",
			"Yearly - Small",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
	WFKdEZEQl: {
		defaultValue: "row",
		displaySegmentedControl: true,
		optionIcons: ["direction-horizontal", "direction-vertical"],
		options: ["row", "column"],
		optionTitles: ["Horizontal", "Vertical"],
		title: "Card Direction",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerSAc3djdp_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...PricingSingleCardFonts,
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:pricing/deck
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {
	base: "or5YGbWPw",
	xl: "HDhMix8q3",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DeckFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var deck_default = ComponentWithRoot;
export { deck_default as default };
