// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'With Dropdown' | 'Phone' | 'No Dropdown' // Variant
 * name?: string // Name
 * link?: string // Link
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-H6F4KFPW.js";
import { Icon } from "../chunks/chunk-KD6F3UC3.js";
import "../chunks/chunk-HR56UER2.js";
import { className, css, fonts } from "../chunks/chunk-APDXW7PB.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-GZZPQ662.js";
import { routes } from "../chunks/chunk-D65PBWLB.js";

// virtual:header/single-menu-item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/pjWddSE1znAftWfmjham/GDA92Ua4phmLgvrmB1la/qMXl04E_1.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	Floating,
	getFonts,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOverlayState,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
var MaterialFonts = getFonts(Icon);
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	gzkwYaV9v: {
		hover: true,
	},
};
var cycleOrder = ["gzkwYaV9v", "v9f6TQzCo", "o72flVFou"];
var serializationHash = "framer-InUmi";
var variantClassNames = {
	gzkwYaV9v: "framer-v-1g2evba",
	o72flVFou: "framer-v-t8dnqg",
	v9f6TQzCo: "framer-v-magi12",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Overlay = ({ children, blockDocumentScrolling, enabled = true }) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"No Dropdown": "o72flVFou",
	"With Dropdown": "gzkwYaV9v",
	Phone: "v9f6TQzCo",
};
var getProps = ({ height, id, link, name1, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		eB83oncZY:
			(_ref = name1 !== null && name1 !== void 0 ? name1 : props.eB83oncZY) !==
				null && _ref !== void 0
				? _ref
				: "Pages",
		PEDUXygUQ: link !== null && link !== void 0 ? link : props.PEDUXygUQ,
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "gzkwYaV9v",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		eB83oncZY,
		PEDUXygUQ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "gzkwYaV9v",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterupml6a = ({ overlay, loadMore }) =>
		activeVariantCallback(async (...args) => {
			setGestureState({
				isHovered: true,
			});
			overlay.show();
		});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["v9f6TQzCo", "o72flVFou"].includes(baseVariant)) return false;
		return true;
	};
	const ref2 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className3, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Overlay blockDocumentScrolling={false} enabled={isDisplayed()}>
					{(overlay) => (
						<_Fragment>
							<Transition value={transition1}>
								<motion.div
									{...restProps}
									{...gestureHandlers}
									className={cx(
										serializationHash,
										...sharedStyleClassNames,
										"framer-1g2evba",
										className4,
										classNames,
									)}
									data-framer-name={"With Dropdown"}
									data-highlight={true}
									id={`${layoutId}-1g2evba`}
									layoutDependency={layoutDependency}
									layoutId={"gzkwYaV9v"}
									onMouseEnter={onMouseEnterupml6a({
										overlay,
									})}
									ref={ref !== null && ref !== void 0 ? ref : ref1}
									style={{
										backgroundColor: "rgba(243, 243, 243, 0)",
										borderBottomLeftRadius: 40,
										borderBottomRightRadius: 40,
										borderTopLeftRadius: 40,
										borderTopRightRadius: 40,
										...style,
									}}
									variants={{
										"gzkwYaV9v-hover": {
											backgroundColor:
												"var(--token-534b8fd2-299e-4515-a761-4a8ebc575caa, rgb(243, 243, 243))",
										},
										v9f6TQzCo: {
											backgroundColor: "rgba(0, 0, 0, 0)",
											borderBottomLeftRadius: 0,
											borderBottomRightRadius: 0,
											borderTopLeftRadius: 0,
											borderTopRightRadius: 0,
										},
									}}
									{...addPropertyOverrides(
										{
											"gzkwYaV9v-hover": {
												"data-framer-name": void 0,
											},
											o72flVFou: {
												"data-framer-name": "No Dropdown",
											},
											v9f6TQzCo: {
												"data-framer-name": "Phone",
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-19z4iaj"}
										data-framer-name={"Features"}
										fonts={["Inter", "Inter-Bold"]}
										layoutDependency={layoutDependency}
										layoutId={"v9YI6AdPz"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={eB83oncZY}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												o72flVFou: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-1hqv6yj"}
																data-styles-preset={"z7TVLwHMJ"}
																style={{
																	"--framer-text-alignment": "left",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
																}}
															>
																<Link
																	href={PEDUXygUQ}
																	nodeId={"v9YI6AdPz"}
																	openInNewTab={false}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-187ttrx"}
																		data-styles-preset={"GjS8NjK69"}
																	>
																		<motion.strong>{"Pages"}</motion.strong>
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													),
												},
												v9f6TQzCo: {
													children: (
														<React.Fragment>
															<motion.p
																className={"framer-styles-preset-i4ib5z"}
																data-styles-preset={"BGapq_KsD"}
																style={{
																	"--framer-text-alignment": "left",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
																}}
															>
																<Link
																	href={PEDUXygUQ}
																	nodeId={"v9YI6AdPz"}
																	openInNewTab={false}
																	smoothScroll={false}
																>
																	<motion.a
																		className={"framer-styles-preset-187ttrx"}
																		data-styles-preset={"GjS8NjK69"}
																	>
																		<motion.strong>{"Pages"}</motion.strong>
																	</motion.a>
																</Link>
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1hqv6yj"}
												data-styles-preset={"z7TVLwHMJ"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
												}}
											>
												<motion.strong>{"Pages"}</motion.strong>
											</motion.p>
										</React.Fragment>
									</RichText>
									{isDisplayed() && (
										<ComponentViewportProvider>
											<motion.div
												className={"framer-a6uql2-container"}
												layoutDependency={layoutDependency}
												layoutId={"TSzyDi5sV-container"}
											>
												<Icon
													color={
														"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))"
													}
													height={"100%"}
													iconSearch={"Home"}
													iconSelection={"KeyboardArrowDown"}
													iconStyle15={"Filled"}
													iconStyle2={"Filled"}
													iconStyle7={"Filled"}
													id={"TSzyDi5sV"}
													layoutId={"TSzyDi5sV"}
													mirrored={false}
													selectByList={true}
													style={{
														height: "100%",
														width: "100%",
													}}
													width={"100%"}
												/>
											</motion.div>
										</ComponentViewportProvider>
									)}
									{isDisplayed() && (
										<AnimatePresence>
											{overlay.visible && (
												<Floating
													alignment={"center"}
													anchorRef={
														ref !== null && ref !== void 0 ? ref : ref1
													}
													className={cx(
														serializationHash,
														classNames,
														...sharedStyleClassNames,
													)}
													collisionDetection={false}
													data-framer-portal-id={`${layoutId}-1g2evba`}
													offsetX={45.99998778104782}
													offsetY={10.000004805624485}
													onDismiss={overlay.hide}
													placement={"bottom"}
													portalSelector={"#overlay"}
													safeArea={true}
													zIndex={11}
												>
													<MotionDivWithFX
														__perspectiveFX={false}
														__smartComponentFX={true}
														__targetOpacity={1}
														animate={animation1}
														className={"framer-18ncvoj"}
														data-framer-name={"Menu"}
														exit={animation}
														initial={animation2}
														layoutDependency={layoutDependency}
														layoutId={"vnHxQK1wi"}
														ref={ref2}
														role={"dialog"}
														style={{
															backgroundColor:
																"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
															borderBottomLeftRadius: 12,
															borderBottomRightRadius: 12,
															borderTopLeftRadius: 12,
															borderTopRightRadius: 12,
															boxShadow: "0px 12px 40px 0px rgba(0,0,0,0.25)",
														}}
													>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1wvt654"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"U00n5KaH7"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "augiA20Il",
																		}}
																		nodeId={"U00n5KaH7"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>{"Home"}</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1vxysqs"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"hX38e3Fmc"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "nY2sub35I",
																		}}
																		nodeId={"hX38e3Fmc"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>{"About"}</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1yxxg7r"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"tIEMCzQzR"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "hH6cLvzw7",
																		}}
																		nodeId={"tIEMCzQzR"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>{"Pricing"}</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-6us9q"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"asBY6YaAH"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "D7tACqYJv",
																		}}
																		nodeId={"asBY6YaAH"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>
																				{"Features"}
																			</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-jfo7wo"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"OQin6txSm"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "a_mtZTrsI",
																		}}
																		nodeId={"OQin6txSm"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>{"Blog"}</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-16ncojt"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"YNCnJtW08"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			pathVariables: {
																				YEFCwiUpS:
																					"why-choose-findays-framer-template",
																			},
																			unresolvedPathSlugs: {
																				YEFCwiUpS: {
																					collectionId: "KycNpAtag",
																					collectionItemId: "zAXMA8COW",
																				},
																			},
																			webPageId: "RXUfcYhsR",
																		}}
																		nodeId={"YNCnJtW08"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>
																				{"Blog Details"}
																			</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1371t3j"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"KtGm4jIhd"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "DYqGM29WM",
																		}}
																		nodeId={"KtGm4jIhd"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>
																				{"Changelog"}
																			</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-f0ewdg"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"ILp3QVwiE"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "L3F_ZUarC",
																		}}
																		nodeId={"ILp3QVwiE"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>{"Contact"}</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1tszufo"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"KF974pOY7"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			webPageId: "gXIN0rBt3",
																		}}
																		nodeId={"KF974pOY7"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>{"404"}</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-1vqcc1s"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"XjpwguPRc"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			pathVariables: {
																				xtme87vD5: "privacy-policy",
																			},
																			unresolvedPathSlugs: {
																				xtme87vD5: {
																					collectionId: "wSt72ndmv",
																					collectionItemId: "ITB1_4qtQ",
																				},
																			},
																			webPageId: "HEYWONA3d",
																		}}
																		nodeId={"XjpwguPRc"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>
																				{"Privacy Policy"}
																			</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
														<RichText
															__fromCanvasComponent={true}
															className={"framer-cvr6kt"}
															fonts={["Inter", "Inter-Bold"]}
															layoutDependency={layoutDependency}
															layoutId={"iA4Wb52ku"}
															style={{
																"--framer-paragraph-spacing": "0px",
															}}
															verticalAlignment={"top"}
															withExternalLayout={true}
														>
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1hqv6yj"}
																	data-styles-preset={"z7TVLwHMJ"}
																>
																	<Link
																		href={{
																			pathVariables: {
																				xtme87vD5: "terms-conditions",
																			},
																			unresolvedPathSlugs: {
																				xtme87vD5: {
																					collectionId: "wSt72ndmv",
																					collectionItemId: "uoFUSKlQi",
																				},
																			},
																			webPageId: "HEYWONA3d",
																		}}
																		nodeId={"iA4Wb52ku"}
																		openInNewTab={false}
																		smoothScroll={false}
																	>
																		<motion.a
																			className={"framer-styles-preset-187ttrx"}
																			data-styles-preset={"GjS8NjK69"}
																		>
																			<motion.strong>
																				{"Terms & Conditions"}
																			</motion.strong>
																		</motion.a>
																	</Link>
																</motion.p>
															</React.Fragment>
														</RichText>
													</MotionDivWithFX>
												</Floating>
											)}
										</AnimatePresence>
									)}
								</motion.div>
							</Transition>
						</_Fragment>
					)}
				</Overlay>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-InUmi.framer-s2ozme, .framer-InUmi .framer-s2ozme { display: block; }",
	".framer-InUmi.framer-1g2evba { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: visible; padding: 6px 16px 6px 16px; position: relative; width: min-content; }",
	".framer-InUmi .framer-19z4iaj { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-InUmi .framer-a6uql2-container { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-InUmi .framer-18ncvoj { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 24px; position: relative; width: 240px; will-change: var(--framer-will-change-override, transform); }",
	".framer-InUmi .framer-1wvt654, .framer-InUmi .framer-1vxysqs, .framer-InUmi .framer-1yxxg7r, .framer-InUmi .framer-6us9q, .framer-InUmi .framer-jfo7wo, .framer-InUmi .framer-16ncojt, .framer-InUmi .framer-1371t3j, .framer-InUmi .framer-f0ewdg, .framer-InUmi .framer-1tszufo, .framer-InUmi .framer-1vqcc1s, .framer-InUmi .framer-cvr6kt { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-InUmi.framer-1g2evba, .framer-InUmi .framer-18ncvoj { gap: 0px; } .framer-InUmi.framer-1g2evba > * { margin: 0px; margin-left: calc(2px / 2); margin-right: calc(2px / 2); } .framer-InUmi.framer-1g2evba > :first-child { margin-left: 0px; } .framer-InUmi.framer-1g2evba > :last-child { margin-right: 0px; } .framer-InUmi .framer-18ncvoj > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-InUmi .framer-18ncvoj > :first-child { margin-top: 0px; } .framer-InUmi .framer-18ncvoj > :last-child { margin-bottom: 0px; } }",
	".framer-InUmi.framer-v-magi12.framer-1g2evba { cursor: unset; justify-content: flex-start; padding: 0px; }",
	".framer-InUmi.framer-v-t8dnqg.framer-1g2evba { cursor: unset; }",
	...css,
	...css3,
	...css2,
];
var FramerqMXl04E_1 = withCSS(Component, css4, "framer-InUmi");
var stdin_default = FramerqMXl04E_1;
FramerqMXl04E_1.displayName = "Header/Single Menu Item";
FramerqMXl04E_1.defaultProps = {
	height: 41,
	width: 108,
};
addPropertyControls(FramerqMXl04E_1, {
	variant: {
		options: ["gzkwYaV9v", "v9f6TQzCo", "o72flVFou"],
		optionTitles: ["With Dropdown", "Phone", "No Dropdown"],
		title: "Variant",
		type: ControlType.Enum,
	},
	eB83oncZY: {
		defaultValue: "Pages",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	PEDUXygUQ: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerqMXl04E_1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...MaterialFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header/single-menu-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {
	base: "gzkwYaV9v",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SingleMenuItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var single_menu_item_default = ComponentWithRoot;
export { single_menu_item_default as default };
