// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * name?: string // Name
 * position?: string // Position
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-5ETCZXGB.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-XVXSSQMC.js";
import { routes } from "../chunks/chunk-D65PBWLB.js";

// virtual:team/card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/izSu7Bd429EhDWBhTttr/7tbOYj1SVEZ8d1Yiv1V7/YTPGrKRUv.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-4scvw";
var variantClassNames = {
	fPR_D_baL: "framer-v-vgrs7o",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, image, name1, position, width, ...props }) => {
	var _ref, _ref1, _ref2;
	return {
		...props,
		dvxyBuPXP:
			(_ref = name1 !== null && name1 !== void 0 ? name1 : props.dvxyBuPXP) !==
				null && _ref !== void 0
				? _ref
				: "Harry Watshon",
		n6y7P6qZg:
			(_ref1 =
				position !== null && position !== void 0
					? position
					: props.n6y7P6qZg) !== null && _ref1 !== void 0
				? _ref1
				: "Chief Executive Officer",
		u_AOYHQkO:
			(_ref2 = image !== null && image !== void 0 ? image : props.u_AOYHQkO) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						alt: "team member image",
						src: "https://framerusercontent.com/images/AQbkRStucPMd3imxJ528cJlzo1k.png?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/AQbkRStucPMd3imxJ528cJlzo1k.png 485w",
					},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		dvxyBuPXP,
		n6y7P6qZg,
		u_AOYHQkO,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "fPR_D_baL",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-vgrs7o",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"fPR_D_baL"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									((componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.y) || 0) +
										0 +
										0,
								),
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage(u_AOYHQkO),
								...{
									positionX: "center",
									positionY: "center",
								},
							}}
							className={"framer-3cdvzs"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"eZVnNU6a3"}
							style={{
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
						/>
						<motion.div
							className={"framer-12myrg4"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"aDK3Bh4nx"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-r51ez7"}
								data-framer-name={"Harry Watshon"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Q0C5Pukqa"}
								style={{
									"--extracted-1w1cjl5":
										"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={dvxyBuPXP}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-1gntewp"}
										data-styles-preset={"K0scFfTq_"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-1w1cjl5, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
										}}
									>
										{"Harry Watshon"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-16t65pp"}
								data-framer-name={"Chief Executive Officer"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ZjqgZ3Be0"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(77, 79, 78))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={n6y7P6qZg}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1dij33p"}
										data-styles-preset={"O45eiJOu6"}
										style={{
											"--framer-text-alignment": "center",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(77, 79, 78)))",
										}}
									>
										{"Chief Executive Officer"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4scvw.framer-ownhnb, .framer-4scvw .framer-ownhnb { display: block; }",
	".framer-4scvw.framer-vgrs7o { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 270px; }",
	".framer-4scvw .framer-3cdvzs { aspect-ratio: 0.84375 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 320px); overflow: visible; position: relative; width: 100%; }",
	".framer-4scvw .framer-12myrg4 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-4scvw .framer-r51ez7, .framer-4scvw .framer-16t65pp { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-4scvw.framer-vgrs7o, .framer-4scvw .framer-12myrg4 { gap: 0px; } .framer-4scvw.framer-vgrs7o > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-4scvw.framer-vgrs7o > :first-child, .framer-4scvw .framer-12myrg4 > :first-child { margin-top: 0px; } .framer-4scvw.framer-vgrs7o > :last-child, .framer-4scvw .framer-12myrg4 > :last-child { margin-bottom: 0px; } .framer-4scvw .framer-12myrg4 > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } }",
	...css2,
	...css,
];
var FramerYTPGrKRUv = withCSS(Component, css3, "framer-4scvw");
var stdin_default = FramerYTPGrKRUv;
FramerYTPGrKRUv.displayName = "Team/Card";
FramerYTPGrKRUv.defaultProps = {
	height: 405,
	width: 270,
};
addPropertyControls(FramerYTPGrKRUv, {
	dvxyBuPXP: {
		defaultValue: "Harry Watshon",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	n6y7P6qZg: {
		defaultValue: "Chief Executive Officer",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
	u_AOYHQkO: {
		__defaultAssetReference:
			"data:framer/asset-reference,AQbkRStucPMd3imxJ528cJlzo1k.png?originalFilename=Group+2085664662.png&preferredSize=auto",
		__vekterDefault: {
			alt: "team member image",
			assetReference:
				"data:framer/asset-reference,AQbkRStucPMd3imxJ528cJlzo1k.png?originalFilename=Group+2085664662.png&preferredSize=auto",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerYTPGrKRUv,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:team/card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var card_default = ComponentWithRoot;
export { card_default as default };
