// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Small' // Variant
 * name?: string // Name
 * position?: string // Position
 * review?: string // Review
 * avatar?: {src: string, srcSet?: string, alt?: string} // Avatar
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-APDXW7PB.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-QDGUO2RY.js";
import { className, css, fonts } from "../chunks/chunk-5ETCZXGB.js";
import { routes } from "../chunks/chunk-D65PBWLB.js";

// virtual:testimonial/card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/77zYZfmw84BE5lBLiuFE/dScmbzYmKG4V3BZJzf8W/cEJDG_LNL.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["fchXdCvH5", "wUh5l7tQa"];
var serializationHash = "framer-bUJ6j";
var variantClassNames = {
	fchXdCvH5: "framer-v-1337wcq",
	wUh5l7tQa: "framer-v-bhmw4y",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "fchXdCvH5",
	Small: "wUh5l7tQa",
};
var getProps = ({
	avatar,
	height,
	id,
	name1,
	position,
	review,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		hLJMcXmGu:
			(_ref =
				position !== null && position !== void 0
					? position
					: props.hLJMcXmGu) !== null && _ref !== void 0
				? _ref
				: "Entrepreneur",
		I7oTk20Oi:
			(_ref1 =
				review !== null && review !== void 0 ? review : props.I7oTk20Oi) !==
				null && _ref1 !== void 0
				? _ref1
				: "The financial insights feature has been a game-changer for me. I can see exactly where my money is going and adjust my spending habits.",
		oo3j1tUAv:
			(_ref2 =
				avatar !== null && avatar !== void 0 ? avatar : props.oo3j1tUAv) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						alt: "client avatar",
						src: "https://framerusercontent.com/images/IQb5wmnR31AhM0qPZdxJwOZUB4.jpg?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/IQb5wmnR31AhM0qPZdxJwOZUB4.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/IQb5wmnR31AhM0qPZdxJwOZUB4.jpg 1024w",
					},
		PUNqHqXbW:
			(_ref3 = name1 !== null && name1 !== void 0 ? name1 : props.PUNqHqXbW) !==
				null && _ref3 !== void 0
				? _ref3
				: "James Luka",
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "fchXdCvH5",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		PUNqHqXbW,
		hLJMcXmGu,
		I7oTk20Oi,
		oo3j1tUAv,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fchXdCvH5",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className, className3];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1337wcq",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fchXdCvH5"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-de8a06a8-03a7-4559-b5c6-f6a9df9c6d66, rgb(236, 236, 236))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
						{...addPropertyOverrides(
							{
								wUh5l7tQa: {
									"data-framer-name": "Small",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-ju2u3t"}
							data-framer-name={
								"The financial insights feature has been a game-changer for me. I can see exactly where my money is going and adjust my spending habits. I've never missed a payment, and my savings are growing."
							}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"q52IcZBFd"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(77, 79, 78))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={I7oTk20Oi}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									wUh5l7tQa: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1dij33p"}
													data-styles-preset={"O45eiJOu6"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(77, 79, 78)))",
													}}
												>
													{
														"The financial insights feature has been a game-changer for me. I can see exactly where my money is going and adjust my spending habits."
													}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1hqv6yj"}
									data-styles-preset={"z7TVLwHMJ"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(77, 79, 78)))",
									}}
								>
									{
										"The financial insights feature has been a game-changer for me. I can see exactly where my money is going and adjust my spending habits."
									}
								</motion.p>
							</React.Fragment>
						</RichText>
						<motion.div
							className={"framer-acfno8"}
							data-framer-name={"Client"}
							layoutDependency={layoutDependency}
							layoutId={"D5WsdXnTk"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											32 +
											168 +
											106,
									),
									sizes: "60px",
									...toResponsiveImage(oo3j1tUAv),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-s9yeh8"}
								data-framer-name={"Avatar / Image-60"}
								layoutDependency={layoutDependency}
								layoutId={"sF1KgeRAM"}
								style={{
									borderBottomLeftRadius: 30,
									borderBottomRightRadius: 30,
									borderTopLeftRadius: 30,
									borderTopRightRadius: 30,
								}}
								{...addPropertyOverrides(
									{
										wUh5l7tQa: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														22 +
														144 +
														88,
												),
												sizes: "40px",
												...toResponsiveImage(oo3j1tUAv),
												...{
													positionX: "center",
													positionY: "center",
												},
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-kvm7y"}
								data-framer-name={"Title Text"}
								layoutDependency={layoutDependency}
								layoutId={"yKZUBUfEf"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-y5wpot"}
									data-framer-name={"James Luka"}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"tbBLYjcQN"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									text={PUNqHqXbW}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											wUh5l7tQa: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1dij33p"}
															data-styles-preset={"O45eiJOu6"}
														>
															<motion.strong>{"James Luka"}</motion.strong>
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1hqv6yj"}
											data-styles-preset={"z7TVLwHMJ"}
										>
											<motion.strong>{"James Luka"}</motion.strong>
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-k30p0t"}
									data-framer-name={"Entrepreneur"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"kvWpuDpSX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(65, 68, 67))",
										"--framer-paragraph-spacing": "0px",
									}}
									text={hLJMcXmGu}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											wUh5l7tQa: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1ut2zgw"}
															data-styles-preset={"JRs1M1fN4"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(65, 68, 67)))",
															}}
														>
															{"Entrepreneur"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1dij33p"}
											data-styles-preset={"O45eiJOu6"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(65, 68, 67)))",
											}}
										>
											{"Entrepreneur"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bUJ6j.framer-1h6xhpo, .framer-bUJ6j .framer-1h6xhpo { display: block; }",
	".framer-bUJ6j.framer-1337wcq { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 32px; position: relative; width: 406px; }",
	".framer-bUJ6j .framer-ju2u3t, .framer-bUJ6j .framer-y5wpot, .framer-bUJ6j .framer-k30p0t { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-bUJ6j .framer-acfno8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-bUJ6j .framer-s9yeh8 { flex: none; height: 60px; overflow: hidden; position: relative; width: 60px; will-change: var(--framer-will-change-override, transform); }",
	".framer-bUJ6j .framer-kvm7y { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bUJ6j.framer-1337wcq, .framer-bUJ6j .framer-acfno8, .framer-bUJ6j .framer-kvm7y { gap: 0px; } .framer-bUJ6j.framer-1337wcq > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-bUJ6j.framer-1337wcq > :first-child, .framer-bUJ6j .framer-kvm7y > :first-child { margin-top: 0px; } .framer-bUJ6j.framer-1337wcq > :last-child, .framer-bUJ6j .framer-kvm7y > :last-child { margin-bottom: 0px; } .framer-bUJ6j .framer-acfno8 > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-bUJ6j .framer-acfno8 > :first-child { margin-left: 0px; } .framer-bUJ6j .framer-acfno8 > :last-child { margin-right: 0px; } .framer-bUJ6j .framer-kvm7y > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	".framer-bUJ6j.framer-v-bhmw4y.framer-1337wcq { gap: 16px; padding: 22px; }",
	".framer-bUJ6j.framer-v-bhmw4y .framer-s9yeh8 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 40px); width: 40px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bUJ6j.framer-v-bhmw4y.framer-1337wcq { gap: 0px; } .framer-bUJ6j.framer-v-bhmw4y.framer-1337wcq > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-bUJ6j.framer-v-bhmw4y.framer-1337wcq > :first-child { margin-top: 0px; } .framer-bUJ6j.framer-v-bhmw4y.framer-1337wcq > :last-child { margin-bottom: 0px; } }",
	...css2,
	...css,
	...css3,
	'.framer-bUJ6j[data-border="true"]::after, .framer-bUJ6j [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramercEJDG_LNL = withCSS(Component, css4, "framer-bUJ6j");
var stdin_default = FramercEJDG_LNL;
FramercEJDG_LNL.displayName = "Testimonial/Card";
FramercEJDG_LNL.defaultProps = {
	height: 260,
	width: 406,
};
addPropertyControls(FramercEJDG_LNL, {
	variant: {
		options: ["fchXdCvH5", "wUh5l7tQa"],
		optionTitles: ["Desktop", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	PUNqHqXbW: {
		defaultValue: "James Luka",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	hLJMcXmGu: {
		defaultValue: "Entrepreneur",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
	I7oTk20Oi: {
		defaultValue:
			"The financial insights feature has been a game-changer for me. I can see exactly where my money is going and adjust my spending habits.",
		displayTextArea: false,
		title: "Review",
		type: ControlType.String,
	},
	oo3j1tUAv: {
		__defaultAssetReference:
			"data:framer/asset-reference,IQb5wmnR31AhM0qPZdxJwOZUB4.jpg?originalFilename=+Image-60.jpg&preferredSize=auto",
		__vekterDefault: {
			alt: "client avatar",
			assetReference:
				"data:framer/asset-reference,IQb5wmnR31AhM0qPZdxJwOZUB4.jpg?originalFilename=+Image-60.jpg&preferredSize=auto",
		},
		title: "Avatar",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramercEJDG_LNL,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial/card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {
	base: "wUh5l7tQa",
	xl: "fchXdCvH5",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var card_default = ComponentWithRoot;
export { card_default as default };
