// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Small' // Variant
 * title?: string // Title
 * description?: string // Description
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * backgroundColor?: string // Background Color
 * borderColor?: undefined // Border Color
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-2TJ7YMZF.js";
import { className, css, fonts } from "../chunks/chunk-5ETCZXGB.js";
import { routes } from "../chunks/chunk-D65PBWLB.js";

// virtual:feature/card-with-image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jX5RAQsrseqJGyBc1u6h/MFSo4tkxyBcGZMo3ZcHg/TmfniqrQr.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["b3bIrlg4d", "Pmh_rax7C"];
var serializationHash = "framer-PxXyY";
var variantClassNames = {
	b3bIrlg4d: "framer-v-180cfs9",
	Pmh_rax7C: "framer-v-iysw3x",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "b3bIrlg4d",
	Small: "Pmh_rax7C",
};
var getProps = ({
	backgroundColor,
	borderColor,
	description,
	height,
	id,
	image,
	title,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_humanReadableVariantMap_props_variant,
		_ref3,
		_ref4,
		_ref5;
	return {
		...props,
		ayqEk4wE8:
			(_ref =
				borderColor !== null && borderColor !== void 0
					? borderColor
					: props.ayqEk4wE8) !== null && _ref !== void 0
				? _ref
				: {
						borderColor:
							'var(--token-45d8cfdc-f89a-49fc-9496-14d18451fa7f, rgb(222, 241, 223)) /* {"name":"Green Stroke"} */',
						borderStyle: "solid",
						borderWidth: 1,
					},
		enCn7vRWA:
			(_ref1 =
				backgroundColor !== null && backgroundColor !== void 0
					? backgroundColor
					: props.enCn7vRWA) !== null && _ref1 !== void 0
				? _ref1
				: "var(--token-efb823ac-0cb7-4f67-94e2-38d882a48a16, rgb(234, 254, 235))",
		OtNpyMMAM:
			(_ref2 = image !== null && image !== void 0 ? image : props.OtNpyMMAM) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/x82xMeF3p6BrBpZxg8DhiT4VbQ.png",
						srcSet:
							"https://framerusercontent.com/images/x82xMeF3p6BrBpZxg8DhiT4VbQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/x82xMeF3p6BrBpZxg8DhiT4VbQ.png 1024w",
					},
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "b3bIrlg4d",
		x7uD45RTF:
			(_ref4 = title !== null && title !== void 0 ? title : props.x7uD45RTF) !==
				null && _ref4 !== void 0
				? _ref4
				: "Savings Goals & Automation",
		ZfXwrGcgo:
			(_ref5 =
				description !== null && description !== void 0
					? description
					: props.ZfXwrGcgo) !== null && _ref5 !== void 0
				? _ref5
				: "Set and monitor savings goals, whether for a rainy day, a dream vacation, or an emergency fund. Our platform automates transfers to your savings to make reaching those goals easier.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants = motion.create(React.Fragment);
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		x7uD45RTF,
		ZfXwrGcgo,
		OtNpyMMAM,
		enCn7vRWA,
		ayqEk4wE8,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "b3bIrlg4d",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	var _ayqEk4wE8_borderBottomWidth,
		_ayqEk4wE8_borderLeftWidth,
		_ayqEk4wE8_borderRightWidth,
		_ayqEk4wE8_borderTopWidth;
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-180cfs9",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"b3bIrlg4d"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width":
								((_ayqEk4wE8_borderBottomWidth =
									ayqEk4wE8.borderBottomWidth) !== null &&
								_ayqEk4wE8_borderBottomWidth !== void 0
									? _ayqEk4wE8_borderBottomWidth
									: ayqEk4wE8.borderWidth) + "px",
							"--border-color": ayqEk4wE8.borderColor,
							"--border-left-width":
								((_ayqEk4wE8_borderLeftWidth = ayqEk4wE8.borderLeftWidth) !==
									null && _ayqEk4wE8_borderLeftWidth !== void 0
									? _ayqEk4wE8_borderLeftWidth
									: ayqEk4wE8.borderWidth) + "px",
							"--border-right-width":
								((_ayqEk4wE8_borderRightWidth = ayqEk4wE8.borderRightWidth) !==
									null && _ayqEk4wE8_borderRightWidth !== void 0
									? _ayqEk4wE8_borderRightWidth
									: ayqEk4wE8.borderWidth) + "px",
							"--border-style": ayqEk4wE8.borderStyle,
							"--border-top-width":
								((_ayqEk4wE8_borderTopWidth = ayqEk4wE8.borderTopWidth) !==
									null && _ayqEk4wE8_borderTopWidth !== void 0
									? _ayqEk4wE8_borderTopWidth
									: ayqEk4wE8.borderWidth) + "px",
							backgroundColor: enCn7vRWA,
							borderBottomLeftRadius: 24,
							borderBottomRightRadius: 24,
							borderTopLeftRadius: 24,
							borderTopRightRadius: 24,
							...style,
						}}
						{...addPropertyOverrides(
							{
								Pmh_rax7C: {
									"data-framer-name": "Small",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 441,
								intrinsicWidth: 512,
								loading: getLoadingLazyAtYPosition(
									((componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.y) || 0) +
										40 +
										((((componentViewport === null ||
										componentViewport === void 0
											? void 0
											: componentViewport.height) || 682) -
											80 -
											666.6) /
											2 +
											0 +
											0),
								),
								pixelHeight: 882,
								pixelWidth: 1024,
								sizes: `calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 80px)`,
								...toResponsiveImage(OtNpyMMAM),
								...{
									positionX: "center",
									positionY: "center",
								},
							}}
							className={"framer-16tms00"}
							data-border={true}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"gtuf__WYT"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-de8a06a8-03a7-4559-b5c6-f6a9df9c6d66, rgb(236, 236, 236))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
							}}
							{...addPropertyOverrides(
								{
									Pmh_rax7C: {
										background: {
											alt: "",
											fit: "fill",
											intrinsicHeight: 441,
											intrinsicWidth: 512,
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) +
													24 +
													((((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 657) -
														48 -
														646.6) /
														2 +
														0 +
														0),
											),
											pixelHeight: 882,
											pixelWidth: 1024,
											sizes: `calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 48px)`,
											...toResponsiveImage(OtNpyMMAM),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<motion.div
							className={"framer-12771ro"}
							data-framer-name={"Text Block"}
							layoutDependency={layoutDependency}
							layoutId={"dnDo414cf"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-8r19zc"}
								data-framer-name={"Savings Goals & Automation"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"sVg8BFg6e"}
								style={{
									"--extracted-1eung3n":
										"var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={x7uD45RTF}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h4
										className={"framer-styles-preset-iopcet"}
										data-styles-preset={"JIFHFpWha"}
										style={{
											"--framer-text-color":
												"var(--extracted-1eung3n, var(--token-e745315f-252b-4bf3-849d-5e514c4f4704, rgb(14, 16, 15)))",
										}}
									>
										{"Savings Goals & Automation"}
									</motion.h4>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1jfn1jk"}
								data-framer-name={
									"Set and monitor savings goals, whether for a rainy day, a dream vacation, or an emergency fund. Our platform automates transfers to your savings to make reaching those goals easier."
								}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"qnPAdrIlZ"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(65, 68, 67))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={ZfXwrGcgo}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1dij33p"}
										data-styles-preset={"O45eiJOu6"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-495dc03a-2e6c-4998-a7d4-c0b1865cfe57, rgb(65, 68, 67)))",
										}}
									>
										{
											"Set and monitor savings goals, whether for a rainy day, a dream vacation, or an emergency fund. Our platform automates transfers to your savings to make reaching those goals easier."
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PxXyY.framer-16ookwi, .framer-PxXyY .framer-16ookwi { display: block; }",
	".framer-PxXyY.framer-180cfs9 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: hidden; padding: 40px; position: relative; width: 576px; will-change: var(--framer-will-change-override, transform); }",
	".framer-PxXyY .framer-16tms00 { aspect-ratio: 1.1609977324263039 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 427px); overflow: visible; position: relative; width: 100%; }",
	".framer-PxXyY .framer-12771ro { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PxXyY .framer-8r19zc, .framer-PxXyY .framer-1jfn1jk { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PxXyY.framer-180cfs9, .framer-PxXyY .framer-12771ro { gap: 0px; } .framer-PxXyY.framer-180cfs9 > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-PxXyY.framer-180cfs9 > :first-child, .framer-PxXyY .framer-12771ro > :first-child { margin-top: 0px; } .framer-PxXyY.framer-180cfs9 > :last-child, .framer-PxXyY .framer-12771ro > :last-child { margin-bottom: 0px; } .framer-PxXyY .framer-12771ro > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
	".framer-PxXyY.framer-v-iysw3x.framer-180cfs9 { gap: 24px; padding: 24px; }",
	".framer-PxXyY.framer-v-iysw3x .framer-16tms00 { height: var(--framer-aspect-ratio-supported, 455px); }",
	".framer-PxXyY.framer-v-iysw3x .framer-12771ro { gap: 12px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PxXyY.framer-v-iysw3x.framer-180cfs9, .framer-PxXyY.framer-v-iysw3x .framer-12771ro { gap: 0px; } .framer-PxXyY.framer-v-iysw3x.framer-180cfs9 > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-PxXyY.framer-v-iysw3x.framer-180cfs9 > :first-child, .framer-PxXyY.framer-v-iysw3x .framer-12771ro > :first-child { margin-top: 0px; } .framer-PxXyY.framer-v-iysw3x.framer-180cfs9 > :last-child, .framer-PxXyY.framer-v-iysw3x .framer-12771ro > :last-child { margin-bottom: 0px; } .framer-PxXyY.framer-v-iysw3x .framer-12771ro > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }",
	...css2,
	...css,
	'.framer-PxXyY[data-border="true"]::after, .framer-PxXyY [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerTmfniqrQr = withCSS(Component, css3, "framer-PxXyY");
var stdin_default = FramerTmfniqrQr;
FramerTmfniqrQr.displayName = "Feature/Card with Image";
FramerTmfniqrQr.defaultProps = {
	height: 682,
	width: 576,
};
addPropertyControls(FramerTmfniqrQr, {
	variant: {
		options: ["b3bIrlg4d", "Pmh_rax7C"],
		optionTitles: ["Desktop", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	x7uD45RTF: {
		defaultValue: "Savings Goals & Automation",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	ZfXwrGcgo: {
		defaultValue:
			"Set and monitor savings goals, whether for a rainy day, a dream vacation, or an emergency fund. Our platform automates transfers to your savings to make reaching those goals easier.",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	OtNpyMMAM: {
		__defaultAssetReference:
			"data:framer/asset-reference,x82xMeF3p6BrBpZxg8DhiT4VbQ.png?originalFilename=Group+2085664642.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	enCn7vRWA: {
		defaultValue:
			'var(--token-efb823ac-0cb7-4f67-94e2-38d882a48a16, rgb(234, 254, 235)) /* {"name":"Green Bg"} */',
		title: "Background Color",
		type: ControlType.Color,
	},
	ayqEk4wE8: {
		defaultValue: {
			borderColor:
				'var(--token-45d8cfdc-f89a-49fc-9496-14d18451fa7f, rgb(222, 241, 223)) /* {"name":"Green Stroke"} */',
			borderStyle: "solid",
			borderWidth: 1,
		},
		title: "Border Color",
		type: ControlType.Border,
	},
});
addFonts(
	FramerTmfniqrQr,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:feature/card-with-image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {
	base: "Pmh_rax7C",
	xl: "b3bIrlg4d",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CardWithImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var card_with_image_default = ComponentWithRoot;
export { card_with_image_default as default };
