// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Hidden' // Variant
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-APDXW7PB.js";
import { routes } from "./chunks/chunk-D65PBWLB.js";

// virtual:load-more
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tgC5KPWNuRTcFzTI0ZAu/E91h0nKJWsGXJh7rPM9W/wkMVzyjru.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var enabledGestures = {
	hdiOKfOnN: {
		hover: true,
	},
};
var cycleOrder = ["hdiOKfOnN", "YnPGzdRmS", "nOF0kK_yX"];
var serializationHash = "framer-ueLaU";
var variantClassNames = {
	hdiOKfOnN: "framer-v-qs26m1",
	nOF0kK_yX: "framer-v-8qun93",
	YnPGzdRmS: "framer-v-1hmg35o",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "hdiOKfOnN",
	Hidden: "nOF0kK_yX",
	Loading: "YnPGzdRmS",
};
var getProps = ({ click, height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "hdiOKfOnN",
		Wld3NDzSj: click !== null && click !== void 0 ? click : props.Wld3NDzSj,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Wld3NDzSj,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "hdiOKfOnN",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapn9xadi = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Wld3NDzSj) {
			const res = await Wld3NDzSj(...args);
			if (res === false) return false;
		}
	});
	const isDisplayed = () => {
		if (baseVariant === "nOF0kK_yX") return false;
		return true;
	};
	const ref1 = React.useRef(null);
	const isDisplayed1 = () => {
		if (baseVariant === "YnPGzdRmS") return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "YnPGzdRmS") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				{isDisplayed() && (
					<Transition value={transition1}>
						<motion.div
							{...restProps}
							{...gestureHandlers}
							className={cx(
								serializationHash,
								...sharedStyleClassNames,
								"framer-qs26m1",
								className2,
								classNames,
							)}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"hdiOKfOnN"}
							onTap={onTapn9xadi}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								backgroundColor:
									"var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))",
								borderBottomLeftRadius: 50,
								borderBottomRightRadius: 50,
								borderTopLeftRadius: 50,
								borderTopRightRadius: 50,
								...style,
							}}
							variants={{
								"hdiOKfOnN-hover": {
									backgroundColor:
										"var(--token-cd7df16c-63d8-4e01-810f-25702c4e74f4, rgb(0, 71, 27))",
								},
							}}
							{...addPropertyOverrides(
								{
									"hdiOKfOnN-hover": {
										"data-framer-name": void 0,
									},
									YnPGzdRmS: {
										"data-framer-name": "Loading",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{isDisplayed1() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-6tmb18"}
									fonts={["Inter", "Inter-Bold"]}
									layoutDependency={layoutDependency}
									layoutId={"MNJ2UZpyW"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1hqv6yj"}
											data-styles-preset={"z7TVLwHMJ"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)))",
											}}
										>
											<motion.strong>{"Load More"}</motion.strong>
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
							{isDisplayed2() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-1xylc5f"}
									data-framer-appear-id={"1xylc5f"}
									data-framer-name={"Spinner"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"wQu0rzQUV"}
									optimized={true}
									style={{
										mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
										WebkitMask:
											"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
									}}
								>
									<MotionDivWithFX
										__framer__loop={animation2}
										__framer__loopEffectEnabled={true}
										__framer__loopRepeatDelay={0}
										__framer__loopRepeatType={"loop"}
										__framer__loopTransition={transition3}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-sowjju"}
										data-framer-name={"Conic"}
										layoutDependency={layoutDependency}
										layoutId={"RkVRN4j2Z"}
										style={{
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 0deg, rgb(255, 255, 255) 342deg)",
										}}
									>
										<motion.div
											className={"framer-1ghmv1n"}
											data-framer-name={"Round"}
											layoutDependency={layoutDependency}
											layoutId={"vTHfBodLz"}
											style={{
												backgroundColor: "rgb(255, 255, 255)",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
										/>
									</MotionDivWithFX>
								</MotionDivWithFXWithOptimizedAppearEffect>
							)}
						</motion.div>
					</Transition>
				)}
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ueLaU.framer-tf4v32, .framer-ueLaU .framer-tf4v32 { display: block; }",
	".framer-ueLaU.framer-qs26m1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 10px 18px 10px 18px; position: relative; width: min-content; }",
	".framer-ueLaU .framer-6tmb18 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-ueLaU .framer-1xylc5f { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); overflow: visible; position: relative; width: 24px; }",
	".framer-ueLaU .framer-sowjju { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-ueLaU .framer-1ghmv1n { flex: none; height: 2px; left: calc(50.00000000000002% - 2px / 2); overflow: visible; position: absolute; top: 0px; width: 2px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ueLaU.framer-qs26m1 { gap: 0px; } .framer-ueLaU.framer-qs26m1 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-ueLaU.framer-qs26m1 > :first-child { margin-left: 0px; } .framer-ueLaU.framer-qs26m1 > :last-child { margin-right: 0px; } }",
	".framer-ueLaU.framer-v-1hmg35o.framer-qs26m1 { padding: 12px 18px 12px 18px; width: 129px; }",
	...css,
];
var FramerwkMVzyjru = withCSS(Component, css2, "framer-ueLaU");
var stdin_default = FramerwkMVzyjru;
FramerwkMVzyjru.displayName = "Load More";
FramerwkMVzyjru.defaultProps = {
	height: 49,
	width: 128.5,
};
addPropertyControls(FramerwkMVzyjru, {
	variant: {
		options: ["hdiOKfOnN", "YnPGzdRmS", "nOF0kK_yX"],
		optionTitles: ["Default", "Loading", "Hidden"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Wld3NDzSj: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerwkMVzyjru,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:load-more
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {
	base: "hdiOKfOnN",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LoadMoreFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var load_more_default = ComponentWithRoot;
export { load_more_default as default };
