// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * hover?: Function // Hover
}} Props

 */
import { routes } from "./chunks/chunk-D65PBWLB.js";

// virtual:new-template-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/goEGiJxWMxjIrCuvyswg/9BqQWohpisa8Jxt0TDl5/KABI6ATIc.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/3r1MOrsbGq47TYKOPcQV/SlideShow.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { resize } from "@motionone/dom";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import {
	animate,
	LayoutGroup,
	mix,
	motion,
	frame,
	useInView,
	useMotionValue,
	useTransform,
	wrap,
} from "unframer";
import {
	Children,
	cloneElement,
	forwardRef,
	startTransition,
	useCallback,
	useEffect as useEffect2,
	useLayoutEffect,
	useMemo,
	useRef,
	useState as useState2,
} from "react";

// /:https://framerusercontent.com/modules/V9ryrjN5Am9WM1dJeyyJ/GzHgU466IQmt8g4qOKj8/UsePageVisibility.js
import { useState, useEffect } from "react";
var isBrowser = () => typeof document === "object";
function usePageVisibility() {
	if (!isBrowser()) return;
	const [isVisible, setIsVisible] = useState(!document.hidden);
	useEffect(() => {
		const onVisibilityChange = () => setIsVisible(!document.hidden);
		document.addEventListener("visibilitychange", onVisibilityChange, false);
		return () => {
			document.removeEventListener("visibilitychange", onVisibilityChange);
		};
	}, []);
	return isVisible;
}

// /:https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/3r1MOrsbGq47TYKOPcQV/SlideShow.js
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var OPACITY_0 = 1e-3;
function awaitRefCallback(element, controller) {
	let refCallbackResolve;
	const refCallbackPromise = new Promise((resolve, reject) => {
		refCallbackResolve = resolve;
		controller.signal.addEventListener("abort", () => reject);
	}).catch(() => {});
	let current = element.current;
	Object.defineProperty(element, "current", {
		get() {
			return current;
		},
		set(node) {
			current = node;
			if (node === null) {
				controller.abort();
				return;
			}
			refCallbackResolve(node);
		},
		configurable: true,
	});
	return refCallbackPromise;
}
function Slideshow(props) {
	const {
		slots,
		startFrom,
		direction,
		effectsOptions,
		autoPlayControl,
		dragControl,
		alignment,
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		itemAmount,
		fadeOptions,
		intervalControl,
		transitionControl,
		arrowOptions,
		borderRadius,
		progressOptions,
		style,
	} = props;
	const {
		effectsOpacity,
		effectsScale,
		effectsRotate,
		effectsPerspective,
		effectsHover,
	} = effectsOptions;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const {
		showMouseControls,
		arrowSize,
		arrowRadius,
		arrowFill,
		leftArrow,
		rightArrow,
		arrowShouldSpace = true,
		arrowShouldFadeIn = false,
		arrowPosition,
		arrowPadding,
		arrowGap,
		arrowPaddingTop,
		arrowPaddingRight,
		arrowPaddingBottom,
		arrowPaddingLeft,
	} = arrowOptions;
	const {
		showProgressDots,
		dotSize,
		dotsInset,
		dotsRadius,
		dotsPadding,
		dotsGap,
		dotsFill,
		dotsBackground,
		dotsActiveOpacity,
		dotsOpacity,
		dotsBlur,
	} = progressOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const filteredSlots = slots.filter(Boolean);
	const hasChildren = Children.count(filteredSlots) > 0;
	const isHorizontal = direction === "left" || direction === "right";
	const isInverted = direction === "right" || direction === "bottom";
	if (!hasChildren) {
		return (
			<section style={placeholderStyles}>
				<div style={emojiStyles}>{"\u2B50\uFE0F"}</div>
				<p style={titleStyles}>{"Connect to Content"}</p>
				<p style={subtitleStyles}>
					{"Add layers or components to make infinite auto-playing slideshows."}
				</p>
			</section>
		);
	}
	const parentRef = useRef(null);
	const childrenRef = useMemo(() => {
		return filteredSlots.map((index) => ({
			current: null,
		}));
	}, [filteredSlots]);
	const timeoutRef = useRef(void 0);
	const [size, setSize] = useState2({
		parent: null,
		children: null,
		item: null,
		itemWidth: null,
		itemHeight: null,
		viewportLength: null,
	});
	const [isHovering, setIsHovering] = useState2(false);
	const [shouldPlayOnHover, setShouldPlayOnHover] = useState2(autoPlayControl);
	const [isMouseDown, setIsMouseDown] = useState2(false);
	const [isResizing, setIsResizing] = useState2(false);
	const dupedChildren = [];
	let duplicateBy = 4;
	if (isCanvas) {
		duplicateBy = 1;
	}
	const measure = useCallback(() => {
		const firstChild = childrenRef[0].current;
		const lastChild = childrenRef[filteredSlots.length - 1].current;
		if (hasChildren && parentRef.current) {
			const parentLength = isHorizontal
				? parentRef.current.offsetWidth
				: parentRef.current.offsetHeight;
			const start = firstChild
				? isHorizontal
					? firstChild.offsetLeft
					: firstChild.offsetTop
				: 0;
			const end = lastChild
				? isHorizontal
					? lastChild.offsetLeft + lastChild.offsetWidth
					: lastChild.offsetTop + lastChild.offsetHeight
				: 0;
			const childrenLength = end - start + gap;
			const itemSize = firstChild
				? isHorizontal
					? firstChild.offsetWidth
					: firstChild.offsetHeight
				: 0;
			const itemWidth = firstChild ? firstChild.offsetWidth : 0;
			const itemHeight = firstChild ? firstChild.offsetHeight : 0;
			const viewportLength = isHorizontal
				? Math.max(
						document.documentElement.clientWidth || 0,
						__unframerWindow.innerWidth || 0,
						parentRef.current.offsetWidth,
					)
				: Math.max(
						document.documentElement.clientHeight || 0,
						__unframerWindow.innerHeight || 0,
						parentRef.current.offsetHeight,
					);
			startTransition(() =>
				setSize({
					parent: parentLength,
					children: childrenLength,
					item: itemSize,
					itemWidth,
					itemHeight,
					viewportLength,
				}),
			);
		}
	}, [hasChildren]);
	const scheduleMeasure = useCallback(async () => {
		const controller = new AbortController();
		const firstChild = childrenRef[0];
		const lastChild = childrenRef[filteredSlots.length - 1];
		if (!isCanvas && (!firstChild.current || !lastChild.current))
			try {
				await Promise.all([
					awaitRefCallback(firstChild, controller),
					awaitRefCallback(lastChild, controller),
				]);
			} catch {
				controller.abort();
			}
		frame.read(measure);
	}, [measure]);
	useLayoutEffect(() => {
		if (hasChildren) scheduleMeasure();
	}, [hasChildren, itemAmount]);
	const initialResize = useRef(true);
	useEffect2(() => {
		return resize(parentRef.current, ({ contentSize }) => {
			if (!initialResize.current && (contentSize.width || contentSize.height)) {
				scheduleMeasure();
				setIsResizing(true);
			}
			initialResize.current = false;
		});
	}, []);
	useEffect2(() => {
		if (isResizing) {
			const timer = setTimeout(() => setIsResizing(false), 500);
			return () => clearTimeout(timer);
		}
	}, [isResizing]);
	const totalItems =
		filteredSlots === null || filteredSlots === void 0
			? void 0
			: filteredSlots.length;
	const childrenSize = isCanvas
		? 0
		: size === null || size === void 0
			? void 0
			: size.children;
	const itemWithGap =
		(size === null || size === void 0 ? void 0 : size.item) + gap;
	const itemOffset = startFrom * itemWithGap;
	const [currentItem, setCurrentItem] = useState2(startFrom + totalItems);
	const [isDragging, setIsDragging] = useState2(false);
	const visibilityRef = useRef(null);
	const isInView = useInView(visibilityRef);
	const isVisible = usePageVisibility() && isInView;
	const factor = isInverted ? 1 : -1;
	const xOrY = useMotionValue(childrenSize);
	const canvasPosition = isHorizontal
		? -startFrom *
			((size === null || size === void 0 ? void 0 : size.itemWidth) + gap)
		: -startFrom *
			((size === null || size === void 0 ? void 0 : size.itemHeight) + gap);
	const newPosition = () => factor * currentItem * itemWithGap;
	const wrappedValue = !isCanvas
		? useTransform(xOrY, (value) => {
				const wrapped = wrap(-childrenSize, -childrenSize * 2, value);
				return isNaN(wrapped) ? 0 : wrapped;
			})
		: 0;
	const wrappedIndex = wrap(0, totalItems, currentItem);
	const wrappedIndexInverted = wrap(0, -totalItems, currentItem);
	useLayoutEffect(() => {
		if ((size === null || size === void 0 ? void 0 : size.children) === null)
			return;
		if (!initialResize.current && isResizing) {
			xOrY.set(newPosition());
		}
	}, [
		size,
		childrenSize,
		factor,
		itemOffset,
		currentItem,
		itemWithGap,
		isResizing,
	]);
	const switchPages = () => {
		if (isCanvas || !hasChildren || !size.parent || isDragging) return;
		if (xOrY.get() !== newPosition()) {
			animate(xOrY, newPosition(), transitionControl);
		}
		if (autoPlayControl && shouldPlayOnHover) {
			timeoutRef.current = setTimeout(() => {
				setCurrentItem(currentItem + 1);
				switchPages();
			}, intervalControl * 1e3);
		}
	};
	const setDelta = (delta) => {
		if (!isInverted) {
			setCurrentItem(currentItem + delta);
		} else {
			setCurrentItem(currentItem - delta);
		}
	};
	const setPage = (index) => {
		const currentItemWrapped = wrap(0, totalItems, currentItem);
		const currentItemWrappedInvert = wrap(0, -totalItems, currentItem);
		const goto = index - currentItemWrapped;
		const gotoInverted = index - Math.abs(currentItemWrappedInvert);
		if (!isInverted) {
			setCurrentItem(currentItem + goto);
		} else {
			setCurrentItem(currentItem - gotoInverted);
		}
	};
	const handleDragStart = () => {
		setIsDragging(true);
	};
	const handleDragEnd = (event, { offset, velocity }) => {
		setIsDragging(false);
		const offsetXorY = isHorizontal ? offset.x : offset.y;
		const velocityThreshold = 200;
		const velocityXorY = isHorizontal ? velocity.x : velocity.y;
		const isHalfOfNext = offsetXorY < -size.item / 2;
		const isHalfOfPrev = offsetXorY > size.item / 2;
		const normalizedOffset = Math.abs(offsetXorY);
		const itemDelta = Math.round(normalizedOffset / size.item);
		const itemDeltaFromOne = itemDelta === 0 ? 1 : itemDelta;
		if (velocityXorY > velocityThreshold) {
			setDelta(-itemDeltaFromOne);
		} else if (velocityXorY < -velocityThreshold) {
			setDelta(itemDeltaFromOne);
		} else {
			if (isHalfOfNext) {
				setDelta(itemDelta);
			}
			if (isHalfOfPrev) {
				setDelta(-itemDelta);
			}
		}
	};
	useEffect2(() => {
		if (!isVisible || isResizing) return;
		switchPages();
		return () => timeoutRef.current && clearTimeout(timeoutRef.current);
	}, [dupedChildren, isVisible, isResizing]);
	let childCounter = 0;
	const columnOrRowValue = `calc(${100 / itemAmount}% - ${gap}px + ${gap / itemAmount}px)`;
	for (let index = 0; index < duplicateBy; index++) {
		dupedChildren.push(
			...Children.map(filteredSlots, (child, childIndex) => {
				let ref;
				if (childIndex === 0) {
					ref = childrenRef[0];
				}
				if (childIndex === filteredSlots.length - 1) {
					ref = childrenRef[1];
				}
				return (
					<Slide
						ref={childrenRef[childIndex]}
						slideKey={index + childIndex + "lg"}
						index={index}
						width={
							isHorizontal
								? itemAmount > 1
									? columnOrRowValue
									: "100%"
								: "100%"
						}
						height={
							!isHorizontal
								? itemAmount > 1
									? columnOrRowValue
									: "100%"
								: "100%"
						}
						size={size}
						child={child}
						numChildren={
							filteredSlots === null || filteredSlots === void 0
								? void 0
								: filteredSlots.length
						}
						wrappedValue={wrappedValue}
						childCounter={childCounter++}
						gap={gap}
						isCanvas={isCanvas}
						isHorizontal={isHorizontal}
						effectsOpacity={effectsOpacity}
						effectsScale={effectsScale}
						effectsRotate={effectsRotate}
					>
						{index + childIndex}
					</Slide>
				);
			}),
		);
	}
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	const dots = [];
	const dotsBlurStyle = {};
	if (showProgressDots) {
		for (
			let i = 0;
			i <
			(filteredSlots === null || filteredSlots === void 0
				? void 0
				: filteredSlots.length);
			i++
		) {
			dots.push(
				<Dot
					dotStyle={{
						...dotStyle,
						width: dotSize,
						height: dotSize,
						backgroundColor: dotsFill,
					}}
					buttonStyle={baseButtonStyles}
					selectedOpacity={dotsActiveOpacity}
					opacity={dotsOpacity}
					onClick={() => setPage(i)}
					wrappedIndex={wrappedIndex}
					wrappedIndexInverted={wrappedIndexInverted}
					total={totalItems}
					index={i}
					gap={dotsGap}
					padding={dotsPadding}
					isHorizontal={isHorizontal}
					isInverted={isInverted}
				/>,
			);
		}
		if (dotsBlur > 0) {
			dotsBlurStyle.backdropFilter =
				dotsBlurStyle.WebkitBackdropFilter =
				dotsBlurStyle.MozBackdropFilter =
					`blur(${dotsBlur}px)`;
		}
	}
	const dragProps = dragControl
		? {
				drag: isHorizontal ? "x" : "y",
				onDragStart: handleDragStart,
				onDragEnd: handleDragEnd,
				dragDirectionLock: true,
				values: {
					x: xOrY,
					y: xOrY,
				},
				dragMomentum: false,
			}
		: {};
	const arrowHasTop =
		arrowPosition === "top-left" ||
		arrowPosition === "top-mid" ||
		arrowPosition === "top-right";
	const arrowHasBottom =
		arrowPosition === "bottom-left" ||
		arrowPosition === "bottom-mid" ||
		arrowPosition === "bottom-right";
	const arrowHasLeft =
		arrowPosition === "top-left" || arrowPosition === "bottom-left";
	const arrowHasRight =
		arrowPosition === "top-right" || arrowPosition === "bottom-right";
	const arrowHasMid =
		arrowPosition === "top-mid" ||
		arrowPosition === "bottom-mid" ||
		arrowPosition === "auto";
	return (
		<section
			style={{
				...containerStyle,
				padding: paddingValue,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				MozMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				opacity:
					(size === null || size === void 0 ? void 0 : size.item) !== null
						? 1
						: OPACITY_0,
				userSelect: "none",
			}}
			onMouseEnter={() => {
				setIsHovering(true);
				if (!effectsHover) setShouldPlayOnHover(false);
			}}
			onMouseLeave={() => {
				setIsHovering(false);
				if (!effectsHover) setShouldPlayOnHover(true);
			}}
			onMouseDown={(event) => {
				event.preventDefault();
				setIsMouseDown(true);
			}}
			onMouseUp={() => setIsMouseDown(false)}
			ref={visibilityRef}
		>
			<div
				style={{
					width: "100%",
					height: "100%",
					margin: 0,
					padding: "inherit",
					position: "absolute",
					inset: 0,
					overflow: overflow ? "visible" : "hidden",
					borderRadius,
					userSelect: "none",
					perspective: isCanvas ? "none" : effectsPerspective,
				}}
			>
				<motion.ul
					ref={parentRef}
					{...dragProps}
					style={{
						...containerStyle,
						gap,
						placeItems: alignment,
						x: isHorizontal ? (isCanvas ? canvasPosition : wrappedValue) : 0,
						y: !isHorizontal ? (isCanvas ? canvasPosition : wrappedValue) : 0,
						flexDirection: isHorizontal ? "row" : "column",
						transformStyle:
							effectsRotate !== 0 && !isCanvas ? "preserve-3d" : void 0,
						cursor: dragControl ? (isMouseDown ? "grabbing" : "grab") : "auto",
						userSelect: "none",
						...style,
					}}
				>
					{dupedChildren}
				</motion.ul>
			</div>
			<fieldset
				style={{
					...controlsStyles,
				}}
				aria-label={"Slideshow pagination controls"}
				className={"framer--slideshow-controls"}
			>
				<motion.div
					style={{
						position: "absolute",
						display: "flex",
						flexDirection: isHorizontal ? "row" : "column",
						justifyContent: arrowShouldSpace ? "space-between" : "center",
						gap: arrowShouldSpace ? "unset" : arrowGap,
						opacity: arrowShouldFadeIn ? OPACITY_0 : 1,
						alignItems: "center",
						inset: arrowPadding,
						top: arrowShouldSpace
							? arrowPadding
							: arrowHasTop
								? arrowPaddingTop
								: "unset",
						left: arrowShouldSpace
							? arrowPadding
							: arrowHasLeft
								? arrowPaddingLeft
								: arrowHasMid
									? 0
									: "unset",
						right: arrowShouldSpace
							? arrowPadding
							: arrowHasRight
								? arrowPaddingRight
								: arrowHasMid
									? 0
									: "unset",
						bottom: arrowShouldSpace
							? arrowPadding
							: arrowHasBottom
								? arrowPaddingBottom
								: "unset",
					}}
					animate={
						arrowShouldFadeIn && {
							opacity: isHovering ? 1 : OPACITY_0,
						}
					}
					transition={transitionControl}
				>
					<motion.button
						type={"button"}
						style={{
							...baseButtonStyles,
							backgroundColor: arrowFill,
							width: arrowSize,
							height: arrowSize,
							borderRadius: arrowRadius,
							rotate: !isHorizontal ? 90 : 0,
							display: showMouseControls ? "block" : "none",
							pointerEvents: "auto",
						}}
						onClick={() => setDelta(-1)}
						aria-label={"Previous"}
						whileTap={{
							scale: 0.9,
						}}
						transition={{
							duration: 0.15,
						}}
					>
						<img
							decoding={"async"}
							width={arrowSize}
							height={arrowSize}
							src={
								leftArrow ||
								"https://framerusercontent.com/images/6tTbkXggWgQCAJ4DO2QEdXXmgM.svg"
							}
							alt={"Back Arrow"}
						/>
					</motion.button>
					<motion.button
						type={"button"}
						style={{
							...baseButtonStyles,
							backgroundColor: arrowFill,
							width: arrowSize,
							height: arrowSize,
							borderRadius: arrowRadius,
							rotate: !isHorizontal ? 90 : 0,
							display: showMouseControls ? "block" : "none",
							pointerEvents: "auto",
						}}
						onClick={() => setDelta(1)}
						aria-label={"Next"}
						whileTap={{
							scale: 0.9,
						}}
						transition={{
							duration: 0.15,
						}}
					>
						<img
							decoding={"async"}
							width={arrowSize}
							height={arrowSize}
							src={
								rightArrow ||
								"https://framerusercontent.com/images/11KSGbIZoRSg4pjdnUoif6MKHI.svg"
							}
							alt={"Next Arrow"}
						/>
					</motion.button>
				</motion.div>
				{dots.length > 1 ? (
					<div
						style={{
							...dotsContainerStyle,
							left: isHorizontal ? "50%" : dotsInset,
							top: !isHorizontal ? "50%" : "unset",
							transform: isHorizontal ? "translateX(-50%)" : "translateY(-50%)",
							flexDirection: isHorizontal ? "row" : "column",
							bottom: isHorizontal ? dotsInset : "unset",
							borderRadius: dotsRadius,
							backgroundColor: dotsBackground,
							userSelect: "none",
							...dotsBlurStyle,
						}}
					>
						{dots}
					</div>
				) : null}
			</fieldset>
		</section>
	);
}
Slideshow.defaultProps = {
	direction: "left",
	dragControl: false,
	startFrom: 0,
	itemAmount: 1,
	infinity: true,
	gap: 10,
	padding: 10,
	autoPlayControl: true,
	effectsOptions: {
		effectsOpacity: 1,
		effectsScale: 1,
		effectsRotate: 0,
		effectsPerspective: 1200,
		effectsHover: true,
	},
	transitionControl: {
		type: "spring",
		stiffness: 200,
		damping: 40,
	},
	fadeOptions: {
		fadeContent: false,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	arrowOptions: {
		showMouseControls: true,
		arrowShouldFadeIn: false,
		arrowShouldSpace: true,
		arrowFill: "rgba(0,0,0,0.2)",
		arrowSize: 40,
	},
	progressOptions: {
		showProgressDots: true,
	},
};
addPropertyControls(Slideshow, {
	slots: {
		type: ControlType.Array,
		title: "Content",
		control: {
			type: ControlType.ComponentInstance,
		},
	},
	direction: {
		type: ControlType.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		displaySegmentedControl: true,
		defaultValue: Slideshow.defaultProps.direction,
	},
	autoPlayControl: {
		type: ControlType.Boolean,
		title: "Auto Play",
		defaultValue: true,
	},
	intervalControl: {
		type: ControlType.Number,
		title: "Interval",
		defaultValue: 1.5,
		min: 0.5,
		max: 10,
		step: 0.1,
		displayStepper: true,
		unit: "s",
		hidden: (props) => !props.autoPlayControl,
	},
	dragControl: {
		type: ControlType.Boolean,
		title: "Draggable",
		defaultValue: false,
	},
	startFrom: {
		type: ControlType.Number,
		title: "Current",
		min: 0,
		max: 10,
		displayStepper: true,
		defaultValue: Slideshow.defaultProps.startFrom,
	},
	effectsOptions: {
		type: ControlType.Object,
		title: "Effects",
		controls: {
			effectsOpacity: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsOpacity,
				min: 0,
				max: 1,
				step: 0.01,
				displayStepper: true,
			},
			effectsScale: {
				type: ControlType.Number,
				title: "Scale",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsScale,
				min: 0,
				max: 1,
				step: 0.01,
				displayStepper: true,
			},
			effectsPerspective: {
				type: ControlType.Number,
				title: "Perspective",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsPerspective,
				min: 200,
				max: 2e3,
				step: 1,
			},
			effectsRotate: {
				type: ControlType.Number,
				title: "Rotate",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsRotate,
				min: -180,
				max: 180,
				step: 1,
			},
			effectsHover: {
				type: ControlType.Boolean,
				title: "On Hover",
				enabledTitle: "Play",
				disabledTitle: "Pause",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsHover,
			},
		},
	},
	alignment: {
		type: ControlType.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	itemAmount: {
		type: ControlType.Number,
		title: "Items",
		min: 1,
		max: 10,
		displayStepper: true,
		defaultValue: Slideshow.defaultProps.itemAmount,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
		min: 0,
	},
	padding: {
		title: "Padding",
		type: ControlType.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		defaultValue: 0,
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Radius",
		min: 0,
		max: 500,
		displayStepper: true,
		defaultValue: 0,
	},
	transitionControl: {
		type: ControlType.Transition,
		defaultValue: Slideshow.defaultProps.transitionControl,
		title: "Transition",
	},
	fadeOptions: {
		type: ControlType.Object,
		title: "Clipping",
		controls: {
			fadeContent: {
				type: ControlType.Boolean,
				title: "Fade",
				defaultValue: false,
			},
			overflow: {
				type: ControlType.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
	arrowOptions: {
		type: ControlType.Object,
		title: "Arrows",
		controls: {
			showMouseControls: {
				type: ControlType.Boolean,
				title: "Show",
				defaultValue: Slideshow.defaultProps.arrowOptions.showMouseControls,
			},
			arrowFill: {
				type: ControlType.Color,
				title: "Fill",
				hidden: (props) => !props.showMouseControls,
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowFill,
			},
			leftArrow: {
				type: ControlType.Image,
				title: "Previous",
				hidden: (props) => !props.showMouseControls,
			},
			rightArrow: {
				type: ControlType.Image,
				title: "Next",
				hidden: (props) => !props.showMouseControls,
			},
			arrowSize: {
				type: ControlType.Number,
				title: "Size",
				min: 0,
				max: 200,
				displayStepper: true,
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowSize,
				hidden: (props) => !props.showMouseControls,
			},
			arrowRadius: {
				type: ControlType.Number,
				title: "Radius",
				min: 0,
				max: 500,
				defaultValue: 40,
				hidden: (props) => !props.showMouseControls,
			},
			arrowShouldFadeIn: {
				type: ControlType.Boolean,
				title: "Fade In",
				defaultValue: false,
				hidden: (props) => !props.showMouseControls,
			},
			arrowShouldSpace: {
				type: ControlType.Boolean,
				title: "Distance",
				enabledTitle: "Space",
				disabledTitle: "Group",
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowShouldSpace,
				hidden: (props) => !props.showMouseControls,
			},
			arrowPosition: {
				type: ControlType.Enum,
				title: "Position",
				options: [
					"auto",
					"top-left",
					"top-mid",
					"top-right",
					"bottom-left",
					"bottom-mid",
					"bottom-right",
				],
				optionTitles: [
					"Center",
					"Top Left",
					"Top Middle",
					"Top Right",
					"Bottom Left",
					"Bottom Middle",
					"Bottom Right",
				],
				hidden: (props) => !props.showMouseControls || props.arrowShouldSpace,
			},
			arrowPadding: {
				type: ControlType.Number,
				title: "Inset",
				min: -100,
				max: 100,
				defaultValue: 20,
				displayStepper: true,
				hidden: (props) => !props.showMouseControls || !props.arrowShouldSpace,
			},
			arrowPaddingTop: {
				type: ControlType.Number,
				title: "Top",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "bottom-mid" ||
					props.arrowPosition === "bottom-left" ||
					props.arrowPosition === "bottom-right",
			},
			arrowPaddingBottom: {
				type: ControlType.Number,
				title: "Bottom",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "top-left" ||
					props.arrowPosition === "top-right",
			},
			arrowPaddingRight: {
				type: ControlType.Number,
				title: "Right",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-left" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "bottom-left" ||
					props.arrowPosition === "bottom-mid",
			},
			arrowPaddingLeft: {
				type: ControlType.Number,
				title: "Left",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-right" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "bottom-right" ||
					props.arrowPosition === "bottom-mid",
			},
			arrowGap: {
				type: ControlType.Number,
				title: "Gap",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showMouseControls || props.arrowShouldSpace,
			},
		},
	},
	progressOptions: {
		type: ControlType.Object,
		title: "Dots",
		controls: {
			showProgressDots: {
				type: ControlType.Boolean,
				title: "Show",
				defaultValue: false,
			},
			dotSize: {
				type: ControlType.Number,
				title: "Size",
				min: 1,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsInset: {
				type: ControlType.Number,
				title: "Inset",
				min: -100,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsGap: {
				type: ControlType.Number,
				title: "Gap",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsPadding: {
				type: ControlType.Number,
				title: "Padding",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsFill: {
				type: ControlType.Color,
				title: "Fill",
				defaultValue: "#fff",
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsBackground: {
				type: ControlType.Color,
				title: "Backdrop",
				defaultValue: "rgba(0,0,0,0.2)",
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsRadius: {
				type: ControlType.Number,
				title: "Radius",
				min: 0,
				max: 200,
				defaultValue: 50,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsOpacity: {
				type: ControlType.Number,
				title: "Opacity",
				min: 0,
				max: 1,
				defaultValue: 0.5,
				step: 0.1,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsActiveOpacity: {
				type: ControlType.Number,
				title: "Current",
				min: 0,
				max: 1,
				defaultValue: 1,
				step: 0.1,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsBlur: {
				type: ControlType.Number,
				title: "Blur",
				min: 0,
				max: 50,
				defaultValue: 0,
				step: 1,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
		},
	},
});
var containerStyle = {
	display: "flex",
	flexDirection: "row",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
	padding: "20px 20px 30px 20px",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 180,
	lineHeight: 1.5,
	textAlign: "center",
};
var baseButtonStyles = {
	border: "none",
	display: "flex",
	placeContent: "center",
	placeItems: "center",
	overflow: "hidden",
	background: "transparent",
	cursor: "pointer",
	margin: 0,
	padding: 0,
};
var controlsStyles = {
	display: "flex",
	justifyContent: "space-between",
	alignItems: "center",
	position: "absolute",
	pointerEvents: "none",
	userSelect: "none",
	top: 0,
	left: 0,
	right: 0,
	bottom: 0,
	border: 0,
	padding: 0,
	margin: 0,
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);
var Slide = /* @__PURE__ */ forwardRef(function Component(props, ref) {
	var _child_props, _child_props1;
	const {
		slideKey,
		width,
		height,
		child,
		size,
		gap,
		wrappedValue,
		numChildren,
		childCounter,
		isCanvas,
		effects,
		effectsOpacity,
		effectsScale,
		effectsRotate,
		isHorizontal,
		isLast,
		index,
	} = props;
	const childOffset =
		((size === null || size === void 0 ? void 0 : size.item) + gap) *
		childCounter;
	const scrollRange = [
		-(size === null || size === void 0 ? void 0 : size.item),
		0,
		(size === null || size === void 0 ? void 0 : size.parent) -
			(size === null || size === void 0 ? void 0 : size.item) +
			gap,
		size === null || size === void 0 ? void 0 : size.parent,
	].map((val) => val - childOffset);
	const rotateY =
		!isCanvas &&
		useTransform(wrappedValue, scrollRange, [
			-effectsRotate,
			0,
			0,
			effectsRotate,
		]);
	const rotateX =
		!isCanvas &&
		useTransform(wrappedValue, scrollRange, [
			effectsRotate,
			0,
			0,
			-effectsRotate,
		]);
	const opacity =
		!isCanvas &&
		useTransform(wrappedValue, scrollRange, [
			effectsOpacity,
			1,
			1,
			effectsOpacity,
		]);
	const scale =
		!isCanvas &&
		useTransform(wrappedValue, scrollRange, [effectsScale, 1, 1, effectsScale]);
	const originXorY =
		!isCanvas && useTransform(wrappedValue, scrollRange, [1, 1, 0, 0]);
	const isVisible =
		!isCanvas &&
		useTransform(
			wrappedValue,
			(latest) => latest >= scrollRange[1] && latest <= scrollRange[2],
		);
	useEffect2(() => {
		if (!isVisible) return;
		return isVisible.on("change", (newValue) => {
			var _ref_current;
			(_ref_current = ref.current) === null || _ref_current === void 0
				? void 0
				: _ref_current.setAttribute("aria-hidden", !newValue);
		});
	}, []);
	const visibility = isCanvas
		? "visible"
		: useTransform(
				wrappedValue,
				[
					scrollRange[0] - size.viewportLength,
					mix(scrollRange[1], scrollRange[2], 0.5),
					scrollRange[3] + size.viewportLength,
				],
				["hidden", "visible", "hidden"],
			);
	return (
		<LayoutGroup inherit={"id"}>
			<li
				style={{
					display: "contents",
				}}
				aria-hidden={index === 0 ? false : true}
			>
				{
					/* @__PURE__ */ cloneElement(
						child,
						{
							ref,
							key: slideKey + "child",
							style: {
								...((_child_props = child.props) === null ||
								_child_props === void 0
									? void 0
									: _child_props.style),
								flexShrink: 0,
								userSelect: "none",
								width,
								height,
								opacity,
								scale,
								originX: isHorizontal ? originXorY : 0.5,
								originY: !isHorizontal ? originXorY : 0.5,
								rotateY: isHorizontal ? rotateY : 0,
								rotateX: !isHorizontal ? rotateX : 0,
								visibility,
							},
							layoutId: child.props.layoutId
								? child.props.layoutId + "-original-" + index
								: void 0,
						},
						(_child_props1 = child.props) === null || _child_props1 === void 0
							? void 0
							: _child_props1.children,
					)
				}
			</li>
		</LayoutGroup>
	);
});
function Dot({
	selectedOpacity,
	opacity,
	total,
	index,
	wrappedIndex,
	wrappedIndexInverted,
	dotStyle: dotStyle2,
	buttonStyle,
	gap,
	padding,
	isHorizontal,
	isInverted,
	...props
}) {
	let isSelected = wrappedIndex === index;
	if (isInverted) {
		isSelected = Math.abs(wrappedIndexInverted) === index;
	}
	const inlinePadding = gap / 2;
	const top = !isHorizontal && index > 0 ? inlinePadding : padding;
	const bottom = !isHorizontal && index !== total - 1 ? inlinePadding : padding;
	const right = isHorizontal && index !== total - 1 ? inlinePadding : padding;
	const left = isHorizontal && index > 0 ? inlinePadding : padding;
	return (
		<button
			aria-label={`Scroll to page ${index + 1}`}
			type={"button"}
			{...props}
			style={{
				...buttonStyle,
				padding: `${top}px ${right}px ${bottom}px ${left}px`,
			}}
		>
			<motion.div
				style={{
					...dotStyle2,
				}}
				initial={false}
				animate={{
					opacity: isSelected ? selectedOpacity : opacity,
				}}
				transition={{
					duration: 0.3,
				}}
			/>
		</button>
	);
}
var dotsContainerStyle = {
	display: "flex",
	placeContent: "center",
	placeItems: "center",
	overflow: "hidden",
	position: "absolute",
	pointerEvents: "auto",
};
var dotStyle = {
	borderRadius: "50%",
	background: "white",
	cursor: "pointer",
	border: "none",
	placeContent: "center",
	placeItems: "center",
	padding: 0,
};

// /:https://framerusercontent.com/modules/goEGiJxWMxjIrCuvyswg/9BqQWohpisa8Jxt0TDl5/KABI6ATIc.js
var SlideshowFonts = getFonts(Slideshow);
var enabledGestures = {
	zFdCWZyJt: {
		hover: true,
	},
};
var serializationHash = "framer-hlMAH";
var variantClassNames = {
	zFdCWZyJt: "framer-v-sg6en3",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var getProps = ({ height, hover, id, width, ...props }) => {
	return {
		...props,
		e_PhRTgWu: hover ?? props.e_PhRTgWu,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, e_PhRTgWu, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "zFdCWZyJt",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1b7cszy = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		if (e_PhRTgWu) {
			const res = await e_PhRTgWu(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-sg6en3",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"zFdCWZyJt"}
						onMouseEnter={onMouseEnter1b7cszy}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1.3px",
							"--border-color": "rgb(46, 46, 46)",
							"--border-left-width": "1.3px",
							"--border-right-width": "1.3px",
							"--border-style": "solid",
							"--border-top-width": "1.3px",
							backgroundColor: "rgb(18, 18, 18)",
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							boxShadow: "0px 4px 6px 0px rgba(0, 0, 0, 0.25)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								"zFdCWZyJt-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1msbctx"}
							layoutDependency={layoutDependency}
							layoutId={"AoJJfAYiT"}
							style={{
								borderTopLeftRadius: 5,
								borderTopRightRadius: 5,
							}}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-3kkfa5-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"GUPp238sD-container"}
									nodeId={"GUPp238sD"}
									rendersWithMotion={true}
									scopeId={"KABI6ATIc"}
								>
									<Slideshow
										alignment={"center"}
										arrowOptions={{
											arrowFill: "rgba(0, 0, 0, 0.2)",
											arrowGap: 10,
											arrowPadding: 20,
											arrowPaddingBottom: 0,
											arrowPaddingLeft: 0,
											arrowPaddingRight: 0,
											arrowPaddingTop: 0,
											arrowPosition: "auto",
											arrowRadius: 40,
											arrowShouldFadeIn: false,
											arrowShouldSpace: true,
											arrowSize: 40,
											showMouseControls: false,
										}}
										autoPlayControl={true}
										borderRadius={0}
										direction={"top"}
										dragControl={false}
										effectsOptions={{
											effectsHover: true,
											effectsOpacity: 1,
											effectsPerspective: 1200,
											effectsRotate: 0,
											effectsScale: 1,
										}}
										fadeOptions={{
											fadeAlpha: 0,
											fadeContent: false,
											fadeInset: 0,
											fadeWidth: 25,
											overflow: false,
										}}
										gap={0}
										height={"100%"}
										id={"GUPp238sD"}
										intervalControl={3}
										itemAmount={1}
										layoutId={"GUPp238sD"}
										padding={0}
										paddingBottom={0}
										paddingLeft={0}
										paddingPerSide={false}
										paddingRight={0}
										paddingTop={0}
										progressOptions={{
											dotsActiveOpacity: 1,
											dotsBackground: "rgba(0, 0, 0, 0.2)",
											dotsBlur: 0,
											dotsFill: "rgb(255, 255, 255)",
											dotsGap: 10,
											dotsInset: 10,
											dotSize: 10,
											dotsOpacity: 0.5,
											dotsPadding: 10,
											dotsRadius: 50,
											showProgressDots: false,
										}}
										slots={[
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 1108,
													intrinsicWidth: 1600,
													pixelHeight: 1800,
													pixelWidth: 2400,
													sizes: "160.2888px",
													src: "https://framerusercontent.com/images/sLqFyqfKcTf6BNUZ6Ow3U7ahajo.png?scale-down-to=2048",
													srcSet:
														"https://framerusercontent.com/images/sLqFyqfKcTf6BNUZ6Ow3U7ahajo.png?scale-down-to=512 512w,https://framerusercontent.com/images/sLqFyqfKcTf6BNUZ6Ow3U7ahajo.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/sLqFyqfKcTf6BNUZ6Ow3U7ahajo.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/sLqFyqfKcTf6BNUZ6Ow3U7ahajo.png 2400w",
												}}
												className={"framer-1oadwqq"}
												data-framer-name={"Cover"}
												layoutDependency={layoutDependency}
												layoutId={"yITpqQoXu"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 1425,
													intrinsicWidth: 2100,
													pixelHeight: 1800,
													pixelWidth: 2400,
													sizes: "160.6316px",
													src: "https://framerusercontent.com/images/9DukdTLl1GExYCZJm78ztZO9YUg.jpg",
													srcSet:
														"https://framerusercontent.com/images/9DukdTLl1GExYCZJm78ztZO9YUg.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/9DukdTLl1GExYCZJm78ztZO9YUg.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/9DukdTLl1GExYCZJm78ztZO9YUg.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/9DukdTLl1GExYCZJm78ztZO9YUg.jpg 2400w",
												}}
												className={"framer-59qqce"}
												data-framer-name={"Screenshot_1"}
												layoutDependency={layoutDependency}
												layoutId={"wvahOEAFm"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 1425,
													intrinsicWidth: 2100,
													pixelHeight: 1800,
													pixelWidth: 2400,
													sizes: "160.6316px",
													src: "https://framerusercontent.com/images/4L0KwobyHITYp4fLLJbvrLdeI.jpg",
													srcSet:
														"https://framerusercontent.com/images/4L0KwobyHITYp4fLLJbvrLdeI.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/4L0KwobyHITYp4fLLJbvrLdeI.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/4L0KwobyHITYp4fLLJbvrLdeI.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/4L0KwobyHITYp4fLLJbvrLdeI.jpg 2400w",
												}}
												className={"framer-26jlbx"}
												data-framer-name={"Screenshot_2"}
												layoutDependency={layoutDependency}
												layoutId={"yqEWi1D7B"}
											/>,
											<Image
												background={{
													alt: "",
													fit: "fill",
													intrinsicHeight: 1425,
													intrinsicWidth: 2100,
													pixelHeight: 1800,
													pixelWidth: 2400,
													sizes: "160.6316px",
													src: "https://framerusercontent.com/images/9eE0CBpumhd8BZftNgUQMGzTy00.jpg",
													srcSet:
														"https://framerusercontent.com/images/9eE0CBpumhd8BZftNgUQMGzTy00.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/9eE0CBpumhd8BZftNgUQMGzTy00.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/9eE0CBpumhd8BZftNgUQMGzTy00.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/9eE0CBpumhd8BZftNgUQMGzTy00.jpg 2400w",
												}}
												className={"framer-16kizre"}
												data-framer-name={"Screenshot_3"}
												layoutDependency={layoutDependency}
												layoutId={"fWB_M_nEG"}
											/>,
										]}
										startFrom={0}
										style={{
											height: "100%",
											width: "100%",
										}}
										transitionControl={{
											damping: 40,
											delay: 0,
											mass: 1,
											stiffness: 200,
											type: "spring",
										}}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.div>
						<motion2.div
							className={"framer-tmia5f"}
							layoutDependency={layoutDependency}
							layoutId={"THKcNrjWz"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-yozcsi"}
								fonts={["FR;InterDisplay-SemiBold"]}
								layoutDependency={layoutDependency}
								layoutId={"ch3Hm0CpY"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"center"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion2.p
										style={{
											"--font-selector": "RlI7SW50ZXJEaXNwbGF5LVNlbWlCb2xk",
											"--framer-font-family":
												'"Inter Display", "Inter Display Placeholder", sans-serif',
											"--framer-font-size": "14px",
											"--framer-font-weight": "600",
											"--framer-line-height": "1em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										{"Free SaaS Template"}
									</motion2.p>
								</React.Fragment>
							</RichText>
						</motion2.div>
						<Link
							href={"https://www.framer.com/marketplace/templates/saatosa/"}
							motionChild={true}
							nodeId={"EQxD3zFht"}
							openInNewTab={true}
							scopeId={"KABI6ATIc"}
						>
							<motion2.a
								className={"framer-drqfd0 framer-q12727"}
								data-framer-name={"Link"}
								layoutDependency={layoutDependency}
								layoutId={"EQxD3zFht"}
							/>
						</Link>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-hlMAH.framer-q12727, .framer-hlMAH .framer-q12727 { display: block; }",
	".framer-hlMAH.framer-sg6en3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 7px; height: 120px; justify-content: center; overflow: hidden; padding: 5px; position: relative; width: 142px; will-change: var(--framer-will-change-override, transform); }",
	".framer-hlMAH .framer-1msbctx { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-hlMAH .framer-3kkfa5-container { flex: none; height: 100%; position: relative; width: 100%; }",
	".framer-hlMAH .framer-1oadwqq { align-content: center; align-items: center; aspect-ratio: 1.444043321299639 / 1; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 111px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 160px; }",
	".framer-hlMAH .framer-59qqce, .framer-hlMAH .framer-26jlbx, .framer-hlMAH .framer-16kizre { align-content: center; align-items: center; aspect-ratio: 1.4736842105263157 / 1; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 109px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 160px; }",
	".framer-hlMAH .framer-tmia5f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 1px 0px 1px 0px; position: relative; width: 100%; }",
	".framer-hlMAH .framer-yozcsi { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-hlMAH .framer-drqfd0 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; text-decoration: none; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
	'.framer-hlMAH[data-border="true"]::after, .framer-hlMAH [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerKABI6ATIc = withCSS(Component2, css, "framer-hlMAH");
var stdin_default = FramerKABI6ATIc;
FramerKABI6ATIc.displayName = "New Template Card";
FramerKABI6ATIc.defaultProps = {
	height: 120,
	width: 142,
};
addPropertyControls2(FramerKABI6ATIc, {
	e_PhRTgWu: {
		title: "Hover",
		type: ControlType2.EventHandler,
	},
});
addFonts(
	FramerKABI6ATIc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/gazZKZuUEtvr9ULhdA4SprP0AZ0.woff2",
					weight: "600",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/pe8RoujoPxuTZhqoNzYqHX2MXA.woff2",
					weight: "600",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/teGhWnhH3bCqefKGsIsqFy3hK8.woff2",
					weight: "600",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/qQHxgTnEk6Czu1yW4xS82HQWFOk.woff2",
					weight: "600",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/MJ3N6lfN4iP5Um8rJGqLYl03tE.woff2",
					weight: "600",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/dHHUz45rhM2KCQpj9zttNVlibk.woff2",
					weight: "600",
				},
				{
					family: "Inter Display",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/0SEEmmWc3vovhaai4RlRQSWRrz0.woff2",
					weight: "600",
				},
			],
		},
		...SlideshowFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:new-template-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NewTemplateCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var new_template_card_default = ComponentWithRoot;
export { new_template_card_default as default };
