// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 983cbbdeafefc560 "Findays - Multi Layout SaaS Framer Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'tr'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' | 'Phone' // Variant
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-APDXW7PB.js";
import { routes } from "./chunks/chunk-D65PBWLB.js";

// virtual:submit
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bWOhMb5IswxYtAAD7h0l/dmMKIjrV9jOeR6uocXOA/UO4a_Vkp3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	jWOFZCemD: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = [
	"jWOFZCemD",
	"Bd7r4Ys6R",
	"DZTPWxHD7",
	"BVWGA8qtr",
	"xg6aWg0y0",
	"jmOJZVHq2",
];
var serializationHash = "framer-Bb0aK";
var variantClassNames = {
	Bd7r4Ys6R: "framer-v-18uo334",
	BVWGA8qtr: "framer-v-tbibhg",
	DZTPWxHD7: "framer-v-7la8jw",
	jmOJZVHq2: "framer-v-hauuti",
	jWOFZCemD: "framer-v-bm36ug",
	xg6aWg0y0: "framer-v-w6q3y3",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "jWOFZCemD",
	Disabled: "DZTPWxHD7",
	Error: "xg6aWg0y0",
	Loading: "Bd7r4Ys6R",
	Phone: "jmOJZVHq2",
	Success: "BVWGA8qtr",
};
var getProps = ({ height, id, text, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		I6n_cHcRZ:
			(_ref = text !== null && text !== void 0 ? text : props.I6n_cHcRZ) !==
				null && _ref !== void 0
				? _ref
				: "Send Now",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "jWOFZCemD",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		I6n_cHcRZ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "jWOFZCemD",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "Bd7r4Ys6R") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "Bd7r4Ys6R") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-bm36ug",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"jWOFZCemD"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor:
								"var(--token-29ef2a11-253c-4767-833a-2416d745414f, rgb(7, 115, 49))",
							borderBottomLeftRadius: 45,
							borderBottomRightRadius: 45,
							borderTopLeftRadius: 45,
							borderTopRightRadius: 45,
							opacity: 1,
							...style,
						}}
						variants={{
							"jWOFZCemD-hover": {
								backgroundColor:
									"var(--token-cd7df16c-63d8-4e01-810f-25702c4e74f4, rgb(0, 71, 27))",
							},
							"jWOFZCemD-pressed": {
								backgroundColor:
									"var(--token-cd7df16c-63d8-4e01-810f-25702c4e74f4, rgb(0, 71, 27))",
							},
							DZTPWxHD7: {
								opacity: 0.5,
							},
							xg6aWg0y0: {
								backgroundColor: "rgba(255, 34, 68, 0.15)",
							},
						}}
						{...addPropertyOverrides(
							{
								"jWOFZCemD-hover": {
									"data-framer-name": void 0,
								},
								"jWOFZCemD-pressed": {
									"data-framer-name": void 0,
								},
								Bd7r4Ys6R: {
									"data-framer-name": "Loading",
								},
								BVWGA8qtr: {
									"data-framer-name": "Success",
								},
								DZTPWxHD7: {
									"data-framer-name": "Disabled",
								},
								jmOJZVHq2: {
									"data-framer-name": "Phone",
								},
								xg6aWg0y0: {
									"data-framer-name": "Error",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1jbm8qq"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"u7v_JDMUp"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={I6n_cHcRZ}
								variants={{
									xg6aWg0y0: {
										"--extracted-r6o4lv": "rgb(255, 34, 68)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										BVWGA8qtr: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1hqv6yj"}
														data-styles-preset={"z7TVLwHMJ"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)))",
														}}
													>
														{"Thank You"}
													</motion.p>
												</React.Fragment>
											),
											text: void 0,
										},
										xg6aWg0y0: {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1hqv6yj"}
														data-styles-preset={"z7TVLwHMJ"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, rgb(255, 34, 68))",
														}}
													>
														{"Something went wrong"}
													</motion.p>
												</React.Fragment>
											),
											text: void 0,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1hqv6yj"}
										data-styles-preset={"z7TVLwHMJ"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-8153aca1-f9be-44aa-9525-bc1f313343e2, rgb(255, 255, 255)))",
										}}
									>
										{"Send Now"}
									</motion.p>
								</React.Fragment>
							</RichText>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-hws10z"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"IqymGNsD5"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-8sk0cr"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"BaagyBG0A"}
									style={{
										background:
											"conic-gradient(from 180deg at 50% 50%, #4cf 0deg, #4cf 360deg)",
										backgroundColor: "rgb(68, 204, 255)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										Bd7r4Ys6R: {
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
											backgroundColor: "rgba(0, 0, 0, 0)",
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										className={"framer-1n181sv"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"XNXYCFJ6Z"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Bb0aK.framer-hu7di9, .framer-Bb0aK .framer-hu7di9 { display: block; }",
	".framer-Bb0aK.framer-bm36ug { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 14px 24px 14px 24px; position: relative; width: min-content; }",
	".framer-Bb0aK .framer-1jbm8qq { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-Bb0aK .framer-hws10z { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
	".framer-Bb0aK .framer-8sk0cr { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-Bb0aK .framer-1n181sv { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Bb0aK.framer-bm36ug { gap: 0px; } .framer-Bb0aK.framer-bm36ug > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-Bb0aK.framer-bm36ug > :first-child { margin-left: 0px; } .framer-Bb0aK.framer-bm36ug > :last-child { margin-right: 0px; } }",
	".framer-Bb0aK.framer-v-18uo334.framer-bm36ug { padding: 21px 24px 21px 24px; width: 143px; }",
	".framer-Bb0aK.framer-v-18uo334 .framer-8sk0cr { overflow: hidden; }",
	".framer-Bb0aK.framer-v-tbibhg.framer-bm36ug { padding: 16px 24px 16px 24px; }",
	".framer-Bb0aK.framer-v-w6q3y3.framer-bm36ug { cursor: unset; gap: 0px; overflow: unset; padding: 14px 20px 14px 20px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Bb0aK.framer-v-w6q3y3.framer-bm36ug { gap: 0px; } .framer-Bb0aK.framer-v-w6q3y3.framer-bm36ug > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-Bb0aK.framer-v-w6q3y3.framer-bm36ug > :first-child { margin-left: 0px; } .framer-Bb0aK.framer-v-w6q3y3.framer-bm36ug > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerUO4a_Vkp3 = withCSS(Component, css2, "framer-Bb0aK");
var stdin_default = FramerUO4a_Vkp3;
FramerUO4a_Vkp3.displayName = "Submit";
FramerUO4a_Vkp3.defaultProps = {
	height: 57,
	width: 135.5,
};
addPropertyControls(FramerUO4a_Vkp3, {
	variant: {
		options: [
			"jWOFZCemD",
			"Bd7r4Ys6R",
			"DZTPWxHD7",
			"BVWGA8qtr",
			"xg6aWg0y0",
			"jmOJZVHq2",
		],
		optionTitles: [
			"Default",
			"Loading",
			"Disabled",
			"Success",
			"Error",
			"Phone",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	I6n_cHcRZ: {
		defaultValue: "Send Now",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerUO4a_Vkp3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:submit
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "YHfL8UrPV",
		name: "Turkish (Turkey)",
		slug: "tr",
		code: "tr-TR",
	},
];
var defaultResponsiveVariants = {
	base: "jmOJZVHq2",
	xl: "jWOFZCemD",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SubmitFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"983cbbdeafefc560b5964574fc6255658e467266e7c7c4b88b4c00e403b3f65d"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var submit_default = ComponentWithRoot;
export { submit_default as default };
